defmodule AshEnterprise.Ledger.UserDrainWorker do
  @moduledoc """
  Drains unprocessed rows of the change ledger for `legacy.users`, one
  batch per transaction, handing each row to
  AshEnterprise.Ledger.UserIngestion.

  Generated by `mix ash_strangler.gen.ingester AshEnterprise.Legacy.User`.
  Requires the `oban` dependency and a configured Oban instance.

  ## The wake is a hint; the sweep is the guarantee

  The ledger trigger's `pg_notify` wakes this worker promptly, and a wake
  that arrives while the listener is down is simply missed. That is why
  the periodic sweep exists: enqueue this worker on a cron and let
  `unique:` collapse the overlap with wake-driven jobs, and a missed wake
  costs delay instead of delivery.

      config :my_app, Oban,
        queues: [ash_strangler_ledger: 10],
        plugins: [
          {Oban.Plugins.Cron,
           entries: [%{cron: "*/5 * * * *", job: AshEnterprise.Ledger.UserDrainWorker}]}
        ]

  Wire the wake up beside it:

      config :ash_strangler, ledger_drain: {AshEnterprise.Ledger.UserDrainWorker, :nudge}
  """

  use Oban.Worker, queue: :ash_strangler_ledger, max_attempts: 10, unique: [period: 30]

  alias AshEnterprise.Repo

  @batch_size 200
  @events_table AshStrangler.Sql.Ledger.events_table()

  @impl Oban.Worker
  def perform(_job), do: drain()

  @doc "The listener's wake entry point: enqueue, and return quickly."
  def nudge(_ledger_id) do
    %{} |> new() |> Oban.insert()
  end

  @doc """
  Drains until this relation's backlog is empty, returning
  `{:ok, total_ingested}`.
  """
  def drain(acc \\ 0) do
    case drain_batch() do
      {:ok, 0} -> {:ok, acc}
      {:ok, count} -> drain(acc + count)
      {:error, reason} -> {:error, reason}
    end
  end

  # Claim, ingest and mark in ONE transaction: the claim holds the row
  # locks until the batch commits, so a claimed event is ingested and
  # marked exactly once by this transaction. The flip side is that one
  # poison event rolls the whole batch back — every row stays unprocessed
  # and is retried, which is the at-least-once contract. If ingestion
  # writes to a datastore OUTSIDE this repo, the batch is no longer
  # atomic: make `AshEnterprise.Ledger.UserIngestion.ingest/1` idempotent and mark
  # each row as it succeeds instead.
  defp drain_batch do
    AshEnterprise.Repo.transaction(fn ->
      events = claim()

      Enum.each(events, fn event ->
        case AshEnterprise.Ledger.UserIngestion.ingest(event) do
          {:ok, _} -> :ok
          {:error, reason} -> Repo.rollback({:ingest_failed, event.id, reason})
        end
      end)

      mark_processed(Enum.map(events, & &1.id))
      length(events)
    end)
  end

  # FOR UPDATE SKIP LOCKED: concurrent workers claim disjoint rows instead
  # of racing for the same ones, and a worker that dies releases its claim
  # with its transaction. ORDER BY id is the cursor — events leave the
  # ledger in the order the legacy application created them, and a
  # multi-row legacy transaction shares one transaction_id.
  #
  # The claimed columns are declared once and drive BOTH the select list and
  # the map keys: Postgrex hands column names back as strings, and atomizing
  # strings at runtime (`String.to_existing_atom/1`) only works by accident
  # of whatever else in the VM happened to literalize the same atom. Pinning
  # the atoms here makes the column set a compile-time constant of this
  # module, and the SELECT and the keys cannot drift apart.
  @claim_columns [
    :id,
    :source_schema,
    :source_table,
    :operation,
    :primary_key,
    :old_row,
    :new_row,
    :changed_columns,
    :transaction_id,
    :transaction_timestamp,
    :source_user,
    :actor_confidence
  ]

  defp claim do
    %Postgrex.Result{rows: rows} =
      AshEnterprise.Repo.query!(
        """
        SELECT #{Enum.map_join(@claim_columns, ", ", &to_string/1)}
          FROM #{@events_table}
         WHERE processed_at IS NULL
           AND source_schema = $1
           AND source_table = $2
         ORDER BY id
         LIMIT $3
           FOR UPDATE SKIP LOCKED
        """,
        ["legacy", "users", @batch_size]
      )

    Enum.map(rows, fn row -> @claim_columns |> Enum.zip(row) |> Map.new() end)
  end

  defp mark_processed(ids) do
    AshEnterprise.Repo.query!(
      "UPDATE #{@events_table} SET processed_at = now() WHERE id = ANY($1)",
      [ids]
    )
  end
end
