defmodule AshEnterprise.Ledger.UserIngestion do
  @moduledoc """
  Ingests one row of `AshStrangler.Sql.Ledger.events_table/0` into
  AshEnterprise.Accounts.ProjectedUser, through ordinary Ash actions — and
  records the KYC compliance event the projected row can support.

  Generated by `mix ash_strangler.gen.ingester AshEnterprise.Legacy.User`,
  then finished by hand: the delete path and the row location are as
  generated; the insert/update branch maps the legacy columns onto the
  canonical upsert (`ProjectedUser.project/2`), the mapping the generator
  refuses to guess.

  Actor and provenance are part of the contract, not decoration: every
  action carries `actor:` from `resolve_actor/1`, and the changeset context
  carries the source envelope under `ash_events_metadata`, so the central
  audit log can answer "who wrote this, and out of which legacy
  transaction".

  ## Idempotence

  The drain is at-least-once, so ingestion tolerates replays. The canonical
  write is an upsert on `legacy_id` (a replayed insert is an update, not a
  duplicate), and the compliance event is keyed by the ledger event id in its
  correlation id, so a replay appends a distinguishable evaluation rather
  than corrupting one. The full-path integration test drains the same ledger
  event twice and asserts the finding converges.
  """

  require Logger

  alias AshEnterprise.Accounts.ProjectedUser
  alias AshEnterprise.Compliance.Kyc
  alias AshEnterprise.Legacy.Estate
  alias AshEnterprise.Platform.SystemActor

  @key_namespace "ce41843a-c056-4c3e-9c79-50e7e5f4887c"
  @relation "legacy.users"

  @doc """
  Applies one ledger event. Idempotent by design — the drain is
  at-least-once, so this must tolerate being handed an event it has
  already ingested.
  """
  # This host always attributes: the projection system actor stands in for the
  # legacy process, so `resolve_actor/1` has no `:unattributed` answer here
  # and the generated two-way case is collapsed to the branch that fires.
  def ingest(event) do
    metadata = source_envelope(event)
    {:ok, actor} = resolve_actor(event)
    apply_event(event, metadata, actor: actor)
  end

  # A hard DELETE in the legacy application. At `phase :read_from_legacy` the
  # projected row has no destroy action and the phase plan (§4.8 of the
  # strangler plan) has not commissioned one: `acts_as_paranoid` means the
  # common case is an UPDATE of `deleted_at`, which arrives as an update and
  # is carried honestly by the lifecycle facts. A genuine DELETE is logged and
  # skipped so it cannot poison the batch; the ledger row keeps the record.
  defp apply_event(%{operation: "delete"} = event, _metadata, _actor_opts) do
    Logger.warning(
      "[ledger] legacy.users DELETE for #{inspect(event.primary_key)} observed; " <>
        "no destroy action exists on the projected row at phase :read_from_legacy. " <>
        "Ledger event #{event.id} kept as the record."
    )

    {:ok, :skipped}
  end

  # The mapping the generator refuses to guess: legacy columns → canonical
  # inputs. `event.new_row` is the full row as JSONB (string keys), decoded by
  # the drain.
  defp apply_event(%{operation: operation} = event, metadata, actor_opts)
       when operation in ["insert", "update"] do
    with {:ok, legacy_key} <- fetch_key(event),
         {:ok, row} <- fetch_row(event) do
      project(row, legacy_key, metadata, actor_opts)
    end
  end

  defp project(row, legacy_key, envelope, actor_opts) do
    attrs = %{
      id: derived_id(legacy_key),
      legacy_id: legacy_key,
      login: row["login"],
      email: row["email"],
      full_name: full_name(row),
      legacy_state: row["state"]
    }

    # The envelope goes in as changeset context under `ash_events_metadata`,
    # which `StampCorrelation` merges with the platform's own audit metadata:
    # a run-of-the-mill action option cannot carry it, and this is the seam
    # the audit hook already reads. The ledger's ids are namespaced
    # (`ledger_*`) so they cannot collide with the platform's correlation id.
    opts =
      actor_opts ++
        [
          tenant: Estate.organization_id(),
          authorize?: false
        ]

    result =
      ProjectedUser
      |> Ash.Changeset.for_create(:project, attrs, opts)
      |> Ash.Changeset.set_context(%{ash_events_metadata: audit_metadata(envelope)})
      |> Ash.create()

    with {:ok, projected} <- result do
      # The compliance events ride the same transaction as the canonical
      # write: the drain wraps both, so a finding's evaluation can never
      # reference a projection that did not commit. The same system actor
      # that attributes the projection appends the events, so the
      # EventLog's policies see one actor for one ingestion.
      :ok =
        Kyc.record_from_projection(projected,
          actor: actor_opts[:actor],
          correlation_id: "ledger:#{envelope.source_event_id}"
        )

      {:ok, projected}
    end
  end

  @doc """
  Attributes the ingested write.

  A legacy write has no Ash actor behind it: the `legacy.users` writer was a
  Rails process, and `source_user` names a `legacy.users.id`, which is not a
  platform actor. The honest attribution is the projection system actor —
  the same one the read-model projection uses — with the legacy user id kept
  in the envelope, so "who was it really" stays answerable from the ledger
  row without inventing an actor mapping that does not exist yet.
  """
  def resolve_actor(event), do: {:ok, actor_for(event)}

  defp actor_for(_event), do: SystemActor.projection()

  # The envelope the central audit log's metadata carries, verbatim from the
  # ledger row and namespaced under `ledger_*`. actor_confidence records what
  # resolve_actor/1 could actually claim: the system actor is a role
  # attribution, not a person.
  defp source_envelope(event) do
    %{
      source_event_id: event.id,
      source_table: "#{event.source_schema}.#{event.source_table}",
      source_user: event.source_user,
      transaction_id: event.transaction_id,
      actor_confidence: :system_role_attribution
    }
  end

  defp audit_metadata(envelope) do
    %{
      "ledger_event_id" => envelope.source_event_id,
      "ledger_source_table" => envelope.source_table,
      "ledger_source_user" => envelope.source_user,
      "ledger_transaction_id" => envelope.transaction_id,
      "ledger_actor_confidence" => to_string(envelope.actor_confidence)
    }
    |> Enum.reject(fn {_k, v} -> is_nil(v) end)
    |> Map.new()
  end

  defp fetch_key(event) do
    case event.primary_key do
      %{"id" => legacy_key} -> {:ok, legacy_key}
      other -> {:error, {:unknown_primary_key, other}}
    end
  end

  defp fetch_row(%{new_row: row}) when is_map(row), do: {:ok, row}
  defp fetch_row(%{new_row: nil}), do: {:error, :no_row_image}

  # Same derivation the view uses — through AshStrangler.KeyDerivation, never
  # a re-implementation of the hash. A drift finds no row and raises nothing.
  defp derived_id(legacy_key) do
    AshStrangler.KeyDerivation.uuid_v5(
      @key_namespace,
      AshStrangler.KeyDerivation.name(@relation, legacy_key)
    )
  end

  # SQL's `||` propagates NULL, so the view null-defaults every operand; the
  # ingester matches it byte for byte, because the projected row must read the
  # same whichever path wrote it.
  defp full_name(row) do
    "#{row["first_name"] || ""} #{row["last_name"] || ""}"
  end
end
