defmodule AshEnterprise.Legacy.Twins.Companies do
  @moduledoc """
  The twin for `legacy.companies` — the legacy relation, declared as an
  ordinary Ash resource so a mapping can name its columns and have them mean
  something. See `AshStrangler.Twin`.

  Generated by:

      mix ash_strangler.gen.twin --relation legacy.companies --module AshEnterprise.Legacy.Twins.Companies --domain AshEnterprise.Legacy.Twins --repo AshEnterprise.Repo

  Hand edits are lost the next time that runs. It is a snapshot of a schema
  this application does not own, so it goes stale silently — `mix
  ash_strangler.check` diffs it against `information_schema.columns` and says
  so.
  """

  use Ash.Resource,
    domain: AshEnterprise.Legacy.Twins,
    data_layer: AshPostgres.DataLayer,
    extensions: [AshStrangler.Twin]

  postgres do
    table "companies"
    schema "legacy"
    repo AshEnterprise.Repo
    # Ash does not own this table and never will.
    migrate? false
  end

  actions do
    defaults [:read]
  end

  attributes do
    attribute :id, :integer, primary_key?: true, allow_nil?: false, public?: true

    attribute :name, :string, allow_nil?: false, public?: true

    attribute :parent_id, :integer, public?: true

    attribute :created_at, :naive_datetime, public?: true

    attribute :updated_at, :naive_datetime, public?: true
  end

  relationships do
    belongs_to :parent, AshEnterprise.Legacy.Twins.Companies do
      source_attribute :parent_id
      destination_attribute :id
      define_attribute? false
      public? true
    end
  end
end
