defmodule AshEnterprise.Legacy.Twins.Users do
  @moduledoc """
  The twin for `legacy.users` — the legacy relation, declared as an
  ordinary Ash resource so a mapping can name its columns and have them mean
  something. See `AshStrangler.Twin`.

  Generated by:

      mix ash_strangler.gen.twin --relation legacy.users --module AshEnterprise.Legacy.Twins.Users --domain AshEnterprise.Legacy.Twins --repo AshEnterprise.Repo

  Hand edits are lost the next time that runs. It is a snapshot of a schema
  this application does not own, so it goes stale silently — `mix
  ash_strangler.check` diffs it against `information_schema.columns` and says
  so.
  """

  use Ash.Resource,
    domain: AshEnterprise.Legacy.Twins,
    data_layer: AshPostgres.DataLayer,
    extensions: [AshStrangler.Twin]

  postgres do
    table "users"
    schema "legacy"
    repo AshEnterprise.Repo
    # Ash does not own this table and never will.
    migrate? false
  end

  actions do
    defaults [:read]
  end

  attributes do
    attribute :id, :integer, primary_key?: true, allow_nil?: false, public?: true

    attribute :login, :string, public?: true

    attribute :email, :string, public?: true

    attribute :first_name, :string, public?: true

    attribute :last_name, :string, public?: true

    attribute :crypted_password, :string, public?: true

    attribute :salt, :string, public?: true

    attribute :remember_token, :string, public?: true

    attribute :remember_token_expires_at, :naive_datetime, public?: true

    attribute :activation_code, :string, public?: true

    attribute :activated_at, :naive_datetime, public?: true

    attribute :state, :atom do
      allow_nil? false
      public? true
      constraints one_of: [:passive, :pending, :active, :suspended, :deleted]
    end

    attribute :deleted_at, :naive_datetime, public?: true

    attribute :company_id, :integer, public?: true

    attribute :manager_id, :integer, public?: true

    attribute :created_at, :naive_datetime, public?: true

    attribute :updated_at, :naive_datetime, public?: true
  end

  relationships do
    belongs_to :company, AshEnterprise.Legacy.Twins.Companies do
      source_attribute :company_id
      destination_attribute :id
      define_attribute? false
      public? true
    end

    belongs_to :manager, AshEnterprise.Legacy.Twins.Users do
      source_attribute :manager_id
      destination_attribute :id
      define_attribute? false
      public? true
    end
  end

  identities do
    identity :index_users_on_login, [:login]
  end
end
