import { defineCollection } from 'astro:content';
import { docsLoader } from '@astrojs/starlight/loaders';
import { docsSchema } from '@astrojs/starlight/schema';

// The `docs` collection is generated by `scripts/sync-docs.mjs` (run as
// `prebuild`) from the repo-root `docs/` tree. It is gitignored: edit the
// markdown in `docs/`, not the copy.
export const collections = {
  docs: defineCollection({ loader: docsLoader(), schema: docsSchema() }),
};
