defmodule AshEnterprise.Reference.Currency do
  @moduledoc """
  Generated by `mix cdm.gen.resource` from `priv/cdm/resolved/currency.json`.

  Source: Currency (microsoft/CDM, Currency.cdm.json/Currency).

  This is a starting point, not a finished resource. Per
  `docs/manifesto/02-schema-commons.md`, delete the columns you do not need
  and add the actions, calculations and relationships that are genuinely
  yours before this ships.
  """

  use AshEnterprise.Platform.Resource,
    domain: AshEnterprise.Reference,
    ownership: :organization_owned,
    tenant?: true,
    cdm_entity: "Currency"

  postgres do
    table "currencies"
    repo AshEnterprise.Repo
  end

  attributes do
    uuid_primary_key :id

    attribute :exchange_rate, :decimal do
      allow_nil? false
      public? true
      description "Exchange rate between the transaction currency and the base currency."
    end

    attribute :currency_symbol, :string do
      allow_nil? false
      public? true
      constraints max_length: 10
      description "Symbol for the transaction currency."
    end

    attribute :currency_name, :string do
      allow_nil? false
      public? true
      constraints max_length: 100
      description "Name of the transaction currency."
    end

    attribute :iso_currency_code, :string do
      allow_nil? false
      public? true
      constraints max_length: 5
      description "ISO currency code for the transaction currency."
    end

    attribute :currency_precision, :integer do
      allow_nil? false
      public? true
      description "Number of decimal places that can be used for currency."
    end
  end

  identities do
    identity :unique_iso_currency_code, [:iso_currency_code]
  end

  actions do
    defaults [:read, :destroy]

    default_accept [
      :exchange_rate,
      :currency_symbol,
      :currency_name,
      :iso_currency_code,
      :currency_precision
    ]

    create :create do
      primary? true
    end

    update :update do
      primary? true
    end
  end

  code_interface do
    define :create
    define :read
    define :update
    define :destroy
  end
end
