defmodule AshEnterprise.Reference.LanguageLocale do
  @moduledoc """
  Generated by `mix cdm.gen.resource` from `priv/cdm/resolved/dataverse_language_locale.json`.

  Source: LanguageLocale (MicrosoftDocs/powerapps-docs, reference/entities/languagelocale.md).

  This is a starting point, not a finished resource. Per
  `docs/manifesto/02-schema-commons.md`, delete the columns you do not need
  and add the actions, calculations and relationships that are genuinely
  yours before this ships.
  """

  use AshEnterprise.Platform.Resource,
    domain: AshEnterprise.Reference,
    ownership: :organization_owned,
    tenant?: false,
    cdm_entity: "LanguageLocale"

  postgres do
    table "language_locales"
    repo AshEnterprise.Repo
  end

  attributes do
    uuid_primary_key :id

    attribute :locale_id, :integer do
      allow_nil? false
      public? true
      description "Locale ID"
    end

    attribute :code, :string do
      allow_nil? false
      public? true
      constraints max_length: 100
      description "Code"
    end

    attribute :language, :string do
      allow_nil? false
      public? true
      constraints max_length: 100
      description "Language"
    end

    attribute :name, :string do
      allow_nil? false
      public? true
      constraints max_length: 100
      description "Name"
    end

    attribute :region, :string do
      public? true
      constraints max_length: 100
      description "Region"
    end
  end

  identities do
    identity :unique_locale_id, [:locale_id]
  end

  actions do
    defaults [:read, :destroy]
    default_accept [:locale_id, :code, :language, :name, :region]

    create :create do
      primary? true
    end

    update :update do
      primary? true
    end
  end

  code_interface do
    define :create
    define :read
    define :update
    define :destroy
  end
end
