defmodule AshEnterprise.Reference.TimeZoneDefinition do
  @moduledoc """
  Generated by `mix cdm.gen.resource` from `priv/cdm/resolved/dataverse_time_zone_definition.json`.

  Source: TimeZoneDefinition (MicrosoftDocs/powerapps-docs, reference/entities/timezonedefinition.md).

  This is a starting point, not a finished resource. Per
  `docs/manifesto/02-schema-commons.md`, delete the columns you do not need
  and add the actions, calculations and relationships that are genuinely
  yours before this ships.
  """

  use AshEnterprise.Platform.Resource,
    domain: AshEnterprise.Reference,
    ownership: :none,
    tenant?: false,
    cdm_entity: "TimeZoneDefinition"

  postgres do
    table "time_zone_definitions"
    repo AshEnterprise.Repo
  end

  attributes do
    uuid_primary_key :id

    attribute :bias, :integer do
      public? true
      description "Base time bias of the time zone."
    end

    attribute :daylight_name, :string do
      public? true
      constraints max_length: 100
      description "Time zone name for the daylight time."
    end

    attribute :retired_order, :integer do
      allow_nil? false
      public? true
      description "Order an entry for a time zone definition is retired. 0 for the latest entry."
    end

    attribute :standard_name, :string do
      allow_nil? false
      public? true
      constraints max_length: 100
      description "Time zone name for the standard time."
    end

    attribute :time_zone_code, :integer do
      allow_nil? false
      public? true
      description "Time zone identification code."
    end

    attribute :user_interface_name, :string do
      allow_nil? false
      public? true
      constraints max_length: 100
      description "Display name for the time zone in the Microsoft Windows registry."
    end
  end

  identities do
    identity :unique_time_zone_code, [:time_zone_code]
  end

  actions do
    defaults [:read, :destroy]

    default_accept [
      :bias,
      :daylight_name,
      :retired_order,
      :standard_name,
      :time_zone_code,
      :user_interface_name
    ]

    create :create do
      primary? true
    end

    update :update do
      primary? true
    end
  end

  code_interface do
    define :create
    define :read
    define :update
    define :destroy
  end
end
