defmodule AshEnterprise.Repo.Migrations.AddSystemOneQuestionProposals do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:system_one_question_proposals, primary_key: false) do
      add :organization_id, :uuid, null: false
      add :version_number, :bigint, null: false, default: 1
      add :import_sequence_number, :bigint
      add :overridden_created_on, :utc_datetime_usec
      add :modified_on_behalf_by_id, :uuid
      add :created_on_behalf_by_id, :uuid
      add :modified_by_id, :uuid
      add :created_by_id, :uuid

      add :modified_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :created_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :status, :text, null: false, default: "proposed"
      add :source, :text, null: false
      add :policy_digest, :text, null: false
      add :policy_text, :text, null: false
      add :proposals, {:array, :map}, null: false, default: []
      add :refusal_reason, :text
      add :raw_output, :text
      add :profile, :text, null: false
      add :question_id, :text, null: false
      add :wire_question_hash, :text, null: false

      add :proposed_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    alter table(:system_one_judgments) do
      add :wire_question_hash, :text
      add :shadow_of, :uuid
    end
  end

  def down do
    alter table(:system_one_judgments) do
      remove :shadow_of
      remove :wire_question_hash
    end

    drop table(:system_one_question_proposals)
  end
end
