defmodule AshEnterprise.Repo.Migrations.AddAccessRequests do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:access_requests, primary_key: false) do
      add :organization_id, :uuid, null: false
      add :owning_team_id, :uuid
      add :owning_user_id, :uuid
      add :owner_type, :text, null: false, default: "user"
      add :owner_id, :uuid, null: false
      add :owning_business_unit_id, :uuid
      add :lifecycle_status, :text, null: false, default: "active"
      add :version_number, :bigint, null: false, default: 1
      add :import_sequence_number, :bigint
      add :overridden_created_on, :utc_datetime_usec
      add :modified_on_behalf_by_id, :uuid
      add :created_on_behalf_by_id, :uuid
      add :modified_by_id, :uuid
      add :created_by_id, :uuid

      add :modified_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :created_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :justification, :text, null: false
      add :requested_role_tier, :text, null: false, default: "standard"
      add :risk_tier, :text
      add :decision_outcome, :text
      add :granted_user_role_id, :uuid

      add :requested_role_id,
          references(:roles,
            column: :id,
            name: "access_requests_requested_role_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nothing
          ),
          null: false

      add :scoping_business_unit_id,
          references(:business_units,
            column: :id,
            name: "access_requests_scoping_business_unit_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nothing
          )

      add :archived_at, :utc_datetime_usec
    end
  end

  def down do
    drop constraint(:access_requests, "access_requests_requested_role_id_fkey")

    drop constraint(:access_requests, "access_requests_scoping_business_unit_id_fkey")

    drop table(:access_requests)
  end
end
