defmodule AshEnterprise.Repo.Migrations.AddIdentityAndSecurityDomains do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:user_roles, primary_key: false) do
      add :organization_id, :uuid, null: false
      add :version_number, :bigint, null: false, default: 1
      add :import_sequence_number, :bigint
      add :overridden_created_on, :utc_datetime_usec
      add :modified_on_behalf_by_id, :uuid
      add :created_on_behalf_by_id, :uuid
      add :modified_by_id, :uuid
      add :created_by_id, :uuid

      add :modified_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :created_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :user_id,
          references(:users,
            column: :id,
            name: "user_roles_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :role_id, :uuid, null: false
      add :scoping_business_unit_id, :uuid, null: false
      add :archived_at, :utc_datetime_usec
    end

    create unique_index(
             :user_roles,
             [:organization_id, :user_id, :role_id, :scoping_business_unit_id],
             name: "user_roles_unique_assignment_index"
           )

    create table(:teams, primary_key: false) do
      add :organization_id, :uuid, null: false
      add :owning_business_unit_id, :uuid
      add :status_code, :bigint
      add :state_code, :bigint, null: false, default: 0
      add :version_number, :bigint, null: false, default: 1
      add :import_sequence_number, :bigint
      add :overridden_created_on, :utc_datetime_usec
      add :modified_on_behalf_by_id, :uuid
      add :created_on_behalf_by_id, :uuid
      add :modified_by_id, :uuid
      add :created_by_id, :uuid

      add :modified_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :created_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :description, :text
      add :team_type, :text, null: false, default: "owner"
      add :is_default, :boolean, null: false, default: false
      add :system_managed, :boolean, null: false, default: false
      add :external_directory_object_id, :uuid

      add :administrator_id,
          references(:users,
            column: :id,
            name: "teams_administrator_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :archived_at, :utc_datetime_usec
    end

    create unique_index(:teams, [:organization_id, :owning_business_unit_id, :name],
             name: "teams_unique_name_per_business_unit_index"
           )

    create table(:team_roles, primary_key: false) do
      add :organization_id, :uuid, null: false
      add :version_number, :bigint, null: false, default: 1
      add :import_sequence_number, :bigint
      add :overridden_created_on, :utc_datetime_usec
      add :modified_on_behalf_by_id, :uuid
      add :created_on_behalf_by_id, :uuid
      add :modified_by_id, :uuid
      add :created_by_id, :uuid

      add :modified_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :created_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :team_id,
          references(:teams,
            column: :id,
            name: "team_roles_team_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :role_id, :uuid, null: false
      add :scoping_business_unit_id, :uuid, null: false
      add :archived_at, :utc_datetime_usec
    end

    create unique_index(
             :team_roles,
             [:organization_id, :team_id, :role_id, :scoping_business_unit_id],
             name: "team_roles_unique_assignment_index"
           )

    create table(:team_memberships, primary_key: false) do
      add :organization_id, :uuid, null: false
      add :version_number, :bigint, null: false, default: 1
      add :import_sequence_number, :bigint
      add :overridden_created_on, :utc_datetime_usec
      add :modified_on_behalf_by_id, :uuid
      add :created_on_behalf_by_id, :uuid
      add :modified_by_id, :uuid
      add :created_by_id, :uuid

      add :modified_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :created_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :user_id,
          references(:users,
            column: :id,
            name: "team_memberships_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :team_id,
          references(:teams,
            column: :id,
            name: "team_memberships_team_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :archived_at, :utc_datetime_usec
    end

    create unique_index(:team_memberships, [:organization_id, :user_id, :team_id],
             name: "team_memberships_unique_membership_index"
           )

    create table(:roles, primary_key: false) do
      add :organization_id, :uuid, null: false
      add :owning_business_unit_id, :uuid
      add :status_code, :bigint
      add :state_code, :bigint, null: false, default: 0
      add :version_number, :bigint, null: false, default: 1
      add :import_sequence_number, :bigint
      add :overridden_created_on, :utc_datetime_usec
      add :modified_on_behalf_by_id, :uuid
      add :created_on_behalf_by_id, :uuid
      add :modified_by_id, :uuid
      add :created_by_id, :uuid

      add :modified_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :created_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:user_roles) do
      modify :role_id,
             references(:roles,
               column: :id,
               name: "user_roles_role_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    alter table(:team_roles) do
      modify :role_id,
             references(:roles,
               column: :id,
               name: "team_roles_role_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    alter table(:roles) do
      add :name, :text, null: false
      add :description, :text
      add :is_inherited, :text, null: false, default: "direct_user_and_team"
      add :is_system_generated, :boolean, null: false, default: false
      add :archived_at, :utc_datetime_usec
    end

    create unique_index(:roles, [:organization_id, :owning_business_unit_id, :name],
             name: "roles_unique_name_per_business_unit_index"
           )

    create table(:role_privileges, primary_key: false) do
      add :organization_id, :uuid, null: false
      add :version_number, :bigint, null: false, default: 1
      add :import_sequence_number, :bigint
      add :overridden_created_on, :utc_datetime_usec
      add :modified_on_behalf_by_id, :uuid
      add :created_on_behalf_by_id, :uuid
      add :modified_by_id, :uuid
      add :created_by_id, :uuid

      add :modified_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :created_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :depth, :text, null: false

      add :role_id,
          references(:roles,
            column: :id,
            name: "role_privileges_role_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :privilege_id, :uuid, null: false
      add :archived_at, :utc_datetime_usec
    end

    create unique_index(:role_privileges, [:organization_id, :role_id, :privilege_id],
             name: "role_privileges_unique_grant_index"
           )

    create table(:privileges, primary_key: false) do
      add :version_number, :bigint, null: false, default: 1
      add :import_sequence_number, :bigint
      add :overridden_created_on, :utc_datetime_usec
      add :modified_on_behalf_by_id, :uuid
      add :created_on_behalf_by_id, :uuid
      add :modified_by_id, :uuid
      add :created_by_id, :uuid

      add :modified_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :created_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:role_privileges) do
      modify :privilege_id,
             references(:privileges,
               column: :id,
               name: "role_privileges_privilege_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )
    end

    alter table(:privileges) do
      add :resource_name, :text, null: false
      add :access_right, :text, null: false
      add :name, :text, null: false
      add :can_be_basic, :boolean, null: false, default: true
      add :can_be_local, :boolean, null: false, default: true
      add :can_be_deep, :boolean, null: false, default: true
      add :can_be_global, :boolean, null: false, default: true
    end

    create unique_index(:privileges, [:resource_name, :access_right],
             name: "privileges_unique_privilege_index"
           )

    create table(:organizations, primary_key: false) do
      add :status_code, :bigint
      add :state_code, :bigint, null: false, default: 0
      add :version_number, :bigint, null: false, default: 1
      add :import_sequence_number, :bigint
      add :overridden_created_on, :utc_datetime_usec
      add :modified_on_behalf_by_id, :uuid
      add :created_on_behalf_by_id, :uuid
      add :modified_by_id, :uuid
      add :created_by_id, :uuid

      add :modified_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :created_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :unique_name, :text, null: false
      add :languagelocale_id, :uuid
      add :base_currency_id, :uuid
      add :archived_at, :utc_datetime_usec
    end

    create unique_index(:organizations, [:unique_name], name: "organizations_unique_name_index")

    create table(:business_units, primary_key: false) do
      add :organization_id, :uuid, null: false
      add :owning_business_unit_id, :uuid
      add :status_code, :bigint
      add :state_code, :bigint, null: false, default: 0
      add :version_number, :bigint, null: false, default: 1
      add :import_sequence_number, :bigint
      add :overridden_created_on, :utc_datetime_usec
      add :modified_on_behalf_by_id, :uuid
      add :created_on_behalf_by_id, :uuid
      add :modified_by_id, :uuid
      add :created_by_id, :uuid

      add :modified_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :created_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:user_roles) do
      modify :scoping_business_unit_id,
             references(:business_units,
               column: :id,
               name: "user_roles_scoping_business_unit_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )
    end

    alter table(:team_roles) do
      modify :scoping_business_unit_id,
             references(:business_units,
               column: :id,
               name: "team_roles_scoping_business_unit_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )
    end

    alter table(:business_units) do
      add :name, :text, null: false
      add :path, :text, null: false
      add :depth, :bigint, null: false, default: 0
      add :division_name, :text
      add :cost_center, :text
      add :is_disabled, :boolean, null: false, default: false

      add :parent_business_unit_id,
          references(:business_units,
            column: :id,
            name: "business_units_parent_business_unit_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          )

      add :archived_at, :utc_datetime_usec
    end

    create index(:business_units, [:organization_id, "organization_id", "path"],
             name: "business_units_org_path_prefix_index",
             using: "btree"
           )

    create unique_index(:business_units, [:organization_id, :parent_business_unit_id, :name],
             name: "business_units_unique_name_per_parent_index"
           )

    create table(:access_grants, primary_key: false) do
      add :organization_id, :uuid, null: false
      add :version_number, :bigint, null: false, default: 1
      add :import_sequence_number, :bigint
      add :overridden_created_on, :utc_datetime_usec
      add :modified_on_behalf_by_id, :uuid
      add :created_on_behalf_by_id, :uuid
      add :modified_by_id, :uuid
      add :created_by_id, :uuid

      add :modified_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :created_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :principal_id, :uuid, null: false
      add :principal_type, :text, null: false
      add :resource_name, :text, null: false
      add :record_id, :uuid, null: false
      add :rights_mask, :bigint, null: false, default: 0
      add :inherited_rights_mask, :bigint, null: false, default: 0
      add :archived_at, :utc_datetime_usec
    end

    create index(
             :access_grants,
             [:organization_id, "organization_id", "principal_id", "resource_name"],
             name: "access_grants_principal_index"
           )

    create index(
             :access_grants,
             [:organization_id, "organization_id", "resource_name", "record_id", "principal_id"],
             name: "access_grants_record_principal_index"
           )

    create unique_index(
             :access_grants,
             [:organization_id, :principal_id, :resource_name, :record_id],
             name: "access_grants_unique_grant_index"
           )
  end

  def down do
    drop_if_exists unique_index(
                     :access_grants,
                     [:organization_id, :principal_id, :resource_name, :record_id],
                     name: "access_grants_unique_grant_index"
                   )

    drop_if_exists index(
                     :access_grants,
                     [
                       :organization_id,
                       "organization_id",
                       "resource_name",
                       "record_id",
                       "principal_id"
                     ],
                     name: "access_grants_record_principal_index"
                   )

    drop_if_exists index(
                     :access_grants,
                     [:organization_id, "organization_id", "principal_id", "resource_name"],
                     name: "access_grants_principal_index"
                   )

    drop table(:access_grants)

    drop_if_exists unique_index(
                     :business_units,
                     [:organization_id, :parent_business_unit_id, :name],
                     name: "business_units_unique_name_per_parent_index"
                   )

    drop constraint(:business_units, "business_units_parent_business_unit_id_fkey")

    drop_if_exists index(:business_units, [:organization_id, "organization_id", "path"],
                     name: "business_units_org_path_prefix_index"
                   )

    alter table(:business_units) do
      remove :archived_at
      remove :parent_business_unit_id
      remove :is_disabled
      remove :cost_center
      remove :division_name
      remove :depth
      remove :path
      remove :name
    end

    drop constraint(:team_roles, "team_roles_scoping_business_unit_id_fkey")

    alter table(:team_roles) do
      modify :scoping_business_unit_id, :uuid
    end

    drop constraint(:user_roles, "user_roles_scoping_business_unit_id_fkey")

    alter table(:user_roles) do
      modify :scoping_business_unit_id, :uuid
    end

    drop table(:business_units)

    drop_if_exists unique_index(:organizations, [:unique_name],
                     name: "organizations_unique_name_index"
                   )

    drop table(:organizations)

    drop_if_exists unique_index(:privileges, [:resource_name, :access_right],
                     name: "privileges_unique_privilege_index"
                   )

    alter table(:privileges) do
      remove :can_be_global
      remove :can_be_deep
      remove :can_be_local
      remove :can_be_basic
      remove :name
      remove :access_right
      remove :resource_name
    end

    drop constraint(:role_privileges, "role_privileges_privilege_id_fkey")

    alter table(:role_privileges) do
      modify :privilege_id, :uuid
    end

    drop table(:privileges)

    drop constraint(:role_privileges, "role_privileges_role_id_fkey")

    drop_if_exists unique_index(:role_privileges, [:organization_id, :role_id, :privilege_id],
                     name: "role_privileges_unique_grant_index"
                   )

    drop table(:role_privileges)

    drop_if_exists unique_index(:roles, [:organization_id, :owning_business_unit_id, :name],
                     name: "roles_unique_name_per_business_unit_index"
                   )

    alter table(:roles) do
      remove :archived_at
      remove :is_system_generated
      remove :is_inherited
      remove :description
      remove :name
    end

    drop constraint(:team_roles, "team_roles_role_id_fkey")

    alter table(:team_roles) do
      modify :role_id, :uuid
    end

    drop constraint(:user_roles, "user_roles_role_id_fkey")

    alter table(:user_roles) do
      modify :role_id, :uuid
    end

    drop table(:roles)

    drop constraint(:team_memberships, "team_memberships_user_id_fkey")

    drop constraint(:team_memberships, "team_memberships_team_id_fkey")

    drop_if_exists unique_index(:team_memberships, [:organization_id, :user_id, :team_id],
                     name: "team_memberships_unique_membership_index"
                   )

    drop table(:team_memberships)

    drop constraint(:team_roles, "team_roles_team_id_fkey")

    drop_if_exists unique_index(
                     :team_roles,
                     [:organization_id, :team_id, :role_id, :scoping_business_unit_id],
                     name: "team_roles_unique_assignment_index"
                   )

    drop table(:team_roles)

    drop constraint(:teams, "teams_administrator_id_fkey")

    drop_if_exists unique_index(:teams, [:organization_id, :owning_business_unit_id, :name],
                     name: "teams_unique_name_per_business_unit_index"
                   )

    drop table(:teams)

    drop constraint(:user_roles, "user_roles_user_id_fkey")

    drop_if_exists unique_index(
                     :user_roles,
                     [:organization_id, :user_id, :role_id, :scoping_business_unit_id],
                     name: "user_roles_unique_assignment_index"
                   )

    drop table(:user_roles)
  end
end
