defmodule AshEnterprise.Repo.Migrations.AddPlatformSystemAttributes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :owning_business_unit_id, :uuid
      add :status_code, :bigint
      add :state_code, :bigint, null: false, default: 0
      add :version_number, :bigint, null: false, default: 1
      add :import_sequence_number, :bigint
      add :overridden_created_on, :utc_datetime_usec
      add :modified_on_behalf_by_id, :uuid
      add :created_on_behalf_by_id, :uuid
      add :modified_by_id, :uuid
      add :created_by_id, :uuid

      add :modified_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :created_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:audit_events, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :record_id, :uuid, null: false
      add :version, :bigint, null: false, default: 1
      add :metadata, :map, null: false, default: %{}
      add :data, :map, null: false, default: %{}
      add :changed_attributes, :map, null: false, default: %{}
      add :occurred_at, :utc_datetime_usec, null: false
      add :resource, :text, null: false
      add :action, :text, null: false
      add :action_type, :text, null: false
      add :user_id, :uuid
    end
  end

  def down do
    drop table(:audit_events)

    alter table(:users) do
      remove :created_on
      remove :modified_on
      remove :created_by_id
      remove :modified_by_id
      remove :created_on_behalf_by_id
      remove :modified_on_behalf_by_id
      remove :overridden_created_on
      remove :import_sequence_number
      remove :version_number
      remove :state_code
      remove :status_code
      remove :owning_business_unit_id
    end
  end
end
