defmodule AshEnterprise.Repo.Migrations.AddReferenceDomain do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:time_zone_definitions, primary_key: false) do
      add :lifecycle_status, :text, null: false, default: "active"
      add :version_number, :bigint, null: false, default: 1
      add :import_sequence_number, :bigint
      add :overridden_created_on, :utc_datetime_usec
      add :modified_on_behalf_by_id, :uuid
      add :created_on_behalf_by_id, :uuid
      add :modified_by_id, :uuid
      add :created_by_id, :uuid

      add :modified_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :created_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :bias, :bigint
      add :daylight_name, :text
      add :retired_order, :bigint, null: false
      add :standard_name, :text, null: false
      add :time_zone_code, :bigint, null: false
      add :user_interface_name, :text, null: false
      add :archived_at, :utc_datetime_usec
    end

    create unique_index(:time_zone_definitions, [:time_zone_code],
             name: "time_zone_definitions_unique_time_zone_code_index"
           )

    create table(:language_locales, primary_key: false) do
      add :lifecycle_status, :text, null: false, default: "active"
      add :version_number, :bigint, null: false, default: 1
      add :import_sequence_number, :bigint
      add :overridden_created_on, :utc_datetime_usec
      add :modified_on_behalf_by_id, :uuid
      add :created_on_behalf_by_id, :uuid
      add :modified_by_id, :uuid
      add :created_by_id, :uuid

      add :modified_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :created_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :locale_id, :bigint, null: false
      add :code, :text, null: false
      add :language, :text, null: false
      add :name, :text, null: false
      add :region, :text
      add :archived_at, :utc_datetime_usec
    end

    create unique_index(:language_locales, [:locale_id],
             name: "language_locales_unique_locale_id_index"
           )

    create table(:currencies, primary_key: false) do
      add :organization_id, :uuid, null: false
      add :lifecycle_status, :text, null: false, default: "active"
      add :version_number, :bigint, null: false, default: 1
      add :import_sequence_number, :bigint
      add :overridden_created_on, :utc_datetime_usec
      add :modified_on_behalf_by_id, :uuid
      add :created_on_behalf_by_id, :uuid
      add :modified_by_id, :uuid
      add :created_by_id, :uuid

      add :modified_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :created_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :exchange_rate, :decimal, null: false
      add :currency_symbol, :text, null: false
      add :currency_name, :text, null: false
      add :iso_currency_code, :text, null: false
      add :currency_precision, :bigint, null: false
      add :archived_at, :utc_datetime_usec
    end

    create unique_index(:currencies, [:organization_id, :iso_currency_code],
             name: "currencies_unique_iso_currency_code_index"
           )
  end

  def down do
    drop_if_exists unique_index(:currencies, [:organization_id, :iso_currency_code],
                     name: "currencies_unique_iso_currency_code_index"
                   )

    drop table(:currencies)

    drop_if_exists unique_index(:language_locales, [:locale_id],
                     name: "language_locales_unique_locale_id_index"
                   )

    drop table(:language_locales)

    drop_if_exists unique_index(:time_zone_definitions, [:time_zone_code],
                     name: "time_zone_definitions_unique_time_zone_code_index"
                   )

    drop table(:time_zone_definitions)
  end
end
