defmodule AshEnterprise.Repo.Migrations.AdoptBpmnAndDecisions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:dmn_evaluations, primary_key: false) do
      add :organization_id, :uuid, null: false
      add :version_number, :bigint, null: false, default: 1
      add :import_sequence_number, :bigint
      add :overridden_created_on, :utc_datetime_usec
      add :modified_on_behalf_by_id, :uuid
      add :created_on_behalf_by_id, :uuid
      add :modified_by_id, :uuid
      add :created_by_id, :uuid

      add :modified_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :created_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :definition_id, :uuid, null: false
      add :definition_key, :text, null: false
      add :definition_version, :bigint, null: false
      add :decision_id, :text, null: false
      add :inputs, :map, default: %{}
      add :outputs, :map, default: %{}
      add :matched_rule_ids, {:array, :text}, default: []
      add :hit_policy, :text
      add :duration_us, :bigint
      add :error, :map
      add :correlation_id, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:dmn_evaluations, [:organization_id, :correlation_id])

    create index(:dmn_evaluations, [:organization_id, :definition_id])

    create table(:dmn_definitions, primary_key: false) do
      add :organization_id, :uuid, null: false
      add :version_number, :bigint, null: false, default: 1
      add :import_sequence_number, :bigint
      add :overridden_created_on, :utc_datetime_usec
      add :modified_on_behalf_by_id, :uuid
      add :created_on_behalf_by_id, :uuid
      add :modified_by_id, :uuid
      add :created_by_id, :uuid

      add :modified_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :created_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:dmn_evaluations) do
      modify :definition_id,
             references(:dmn_definitions,
               column: :id,
               name: "dmn_evaluations_definition_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:dmn_definitions) do
      add :key, :text, null: false
      add :name, :text, null: false
      add :version, :bigint, null: false
      add :status, :text, null: false, default: "draft"
      add :xml, :text, null: false
      add :graph, :map
      add :errors, {:array, :map}, default: []
      add :content_hash, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:dmn_definitions, [:organization_id, :key, :status],
             unique: true,
             where: "status = 'draft'"
           )

    create unique_index(:dmn_definitions, [:organization_id, :key, :version],
             name: "dmn_definitions_unique_key_version_index"
           )

    create table(:bpmn_tokens, primary_key: false) do
      add :organization_id, :uuid, null: false
      add :version_number, :bigint, null: false, default: 1
      add :import_sequence_number, :bigint
      add :overridden_created_on, :utc_datetime_usec
      add :modified_on_behalf_by_id, :uuid
      add :created_on_behalf_by_id, :uuid
      add :modified_by_id, :uuid
      add :created_by_id, :uuid

      add :modified_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :created_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :node_id, :text, null: false
      add :status, :text, null: false, default: "active"
      add :parent_token_id, :uuid
      add :fork_id, :uuid
      add :attempts, :bigint, default: 0
      add :routing, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :instance_id, :uuid, null: false
    end

    create table(:bpmn_task_candidates, primary_key: false) do
      add :organization_id, :uuid, null: false
      add :version_number, :bigint, null: false, default: 1
      add :import_sequence_number, :bigint
      add :overridden_created_on, :utc_datetime_usec
      add :modified_on_behalf_by_id, :uuid
      add :created_on_behalf_by_id, :uuid
      add :modified_by_id, :uuid
      add :created_by_id, :uuid

      add :modified_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :created_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :principal_type, :text, null: false
      add :principal_id, :uuid, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :task_id, :uuid, null: false
    end

    create unique_index(
             :bpmn_task_candidates,
             [:organization_id, :task_id, :principal_type, :principal_id],
             name: "bpmn_task_candidates_unique_task_principal_index"
           )

    create table(:bpmn_process_events, primary_key: false) do
      add :organization_id, :uuid, null: false
      add :version_number, :bigint, null: false, default: 1
      add :import_sequence_number, :bigint
      add :overridden_created_on, :utc_datetime_usec
      add :modified_on_behalf_by_id, :uuid
      add :created_on_behalf_by_id, :uuid
      add :modified_by_id, :uuid
      add :created_by_id, :uuid

      add :modified_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :created_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :instance_id, :uuid
      add :token_id, :uuid
      add :node_id, :text
      add :task_id, :uuid
      add :kind, :text, null: false
      add :data, :map, default: %{}

      add :recorded_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:bpmn_instances, primary_key: false) do
      add :organization_id, :uuid, null: false
      add :version_number, :bigint, null: false, default: 1
      add :import_sequence_number, :bigint
      add :overridden_created_on, :utc_datetime_usec
      add :modified_on_behalf_by_id, :uuid
      add :created_on_behalf_by_id, :uuid
      add :modified_by_id, :uuid
      add :created_by_id, :uuid

      add :modified_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :created_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:bpmn_tokens) do
      modify :instance_id,
             references(:bpmn_instances,
               column: :id,
               name: "bpmn_tokens_instance_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:bpmn_process_events) do
      modify :instance_id,
             references(:bpmn_instances,
               column: :id,
               name: "bpmn_process_events_instance_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:bpmn_instances) do
      add :subject_type, :text, null: false
      add :subject_id, :uuid, null: false
      add :correlation_id, :text
      add :status, :text, null: false, default: "running"
      add :started_by_id, :uuid
      add :outcome, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :definition_id, :uuid, null: false
    end

    create table(:bpmn_human_tasks, primary_key: false) do
      add :organization_id, :uuid, null: false
      add :owning_team_id, :uuid
      add :owning_user_id, :uuid
      add :owner_type, :text, null: false, default: "user"
      add :owner_id, :uuid, null: false
      add :owning_business_unit_id, :uuid
      add :version_number, :bigint, null: false, default: 1
      add :import_sequence_number, :bigint
      add :overridden_created_on, :utc_datetime_usec
      add :modified_on_behalf_by_id, :uuid
      add :created_on_behalf_by_id, :uuid
      add :modified_by_id, :uuid
      add :created_by_id, :uuid

      add :modified_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :created_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:bpmn_task_candidates) do
      modify :task_id,
             references(:bpmn_human_tasks,
               column: :id,
               name: "bpmn_task_candidates_task_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:bpmn_human_tasks) do
      add :node_id, :text, null: false
      add :name, :text, null: false
      add :status, :text, null: false, default: "open"
      add :assignee_type, :text
      add :assignee_id, :uuid
      add :claimed_at, :utc_datetime_usec
      add :due_at, :utc_datetime_usec
      add :outcome, :text
      add :decided_by_id, :uuid
      add :delegated_from_id, :uuid
      add :timer_job_ids, {:array, :bigint}, default: []
      add :comment, :text
      add :on_complete, :map, default: %{}
      add :subject_type, :text
      add :subject_id, :uuid

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :instance_id,
          references(:bpmn_instances,
            column: :id,
            name: "bpmn_human_tasks_instance_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :token_id,
          references(:bpmn_tokens,
            column: :id,
            name: "bpmn_human_tasks_token_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create index(:bpmn_human_tasks, [:organization_id, :subject_type, :subject_id, :node_id],
             unique: true,
             where: "status IN ('open','claimed')"
           )

    create table(:bpmn_definitions, primary_key: false) do
      add :organization_id, :uuid, null: false
      add :version_number, :bigint, null: false, default: 1
      add :import_sequence_number, :bigint
      add :overridden_created_on, :utc_datetime_usec
      add :modified_on_behalf_by_id, :uuid
      add :created_on_behalf_by_id, :uuid
      add :modified_by_id, :uuid
      add :created_by_id, :uuid

      add :modified_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :created_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:bpmn_instances) do
      modify :definition_id,
             references(:bpmn_definitions,
               column: :id,
               name: "bpmn_instances_definition_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:bpmn_definitions) do
      add :key, :text, null: false
      add :name, :text, null: false
      add :version, :bigint, null: false
      add :status, :text, null: false, default: "draft"
      add :xml, :text, null: false
      add :graph, :map
      add :errors, {:array, :map}, default: []
      add :content_hash, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:bpmn_definitions, [:organization_id, :key, :status],
             unique: true,
             where: "status = 'draft'"
           )

    create unique_index(:bpmn_definitions, [:organization_id, :key, :version],
             name: "bpmn_definitions_unique_key_version_index"
           )
  end

  def down do
    drop_if_exists unique_index(:bpmn_definitions, [:organization_id, :key, :version],
                     name: "bpmn_definitions_unique_key_version_index"
                   )

    drop_if_exists index(:bpmn_definitions, [:organization_id, :key, :status])

    alter table(:bpmn_definitions) do
      remove :updated_at
      remove :inserted_at
      remove :content_hash
      remove :errors
      remove :graph
      remove :xml
      remove :status
      remove :version
      remove :name
      remove :key
    end

    drop constraint(:bpmn_instances, "bpmn_instances_definition_id_fkey")

    alter table(:bpmn_instances) do
      modify :definition_id, :uuid
    end

    drop table(:bpmn_definitions)

    drop constraint(:bpmn_human_tasks, "bpmn_human_tasks_instance_id_fkey")

    drop constraint(:bpmn_human_tasks, "bpmn_human_tasks_token_id_fkey")

    drop_if_exists index(:bpmn_human_tasks, [
                     :organization_id,
                     :subject_type,
                     :subject_id,
                     :node_id
                   ])

    alter table(:bpmn_human_tasks) do
      remove :token_id
      remove :instance_id
      remove :updated_at
      remove :inserted_at
      remove :subject_id
      remove :subject_type
      remove :on_complete
      remove :comment
      remove :timer_job_ids
      remove :delegated_from_id
      remove :decided_by_id
      remove :outcome
      remove :due_at
      remove :claimed_at
      remove :assignee_id
      remove :assignee_type
      remove :status
      remove :name
      remove :node_id
    end

    drop constraint(:bpmn_task_candidates, "bpmn_task_candidates_task_id_fkey")

    alter table(:bpmn_task_candidates) do
      modify :task_id, :uuid
    end

    drop table(:bpmn_human_tasks)

    alter table(:bpmn_instances) do
      remove :definition_id
      remove :updated_at
      remove :inserted_at
      remove :outcome
      remove :started_by_id
      remove :status
      remove :correlation_id
      remove :subject_id
      remove :subject_type
    end

    drop constraint(:bpmn_process_events, "bpmn_process_events_instance_id_fkey")

    alter table(:bpmn_process_events) do
      modify :instance_id, :uuid
    end

    drop constraint(:bpmn_tokens, "bpmn_tokens_instance_id_fkey")

    alter table(:bpmn_tokens) do
      modify :instance_id, :uuid
    end

    drop table(:bpmn_instances)

    drop table(:bpmn_process_events)

    drop_if_exists unique_index(
                     :bpmn_task_candidates,
                     [:organization_id, :task_id, :principal_type, :principal_id],
                     name: "bpmn_task_candidates_unique_task_principal_index"
                   )

    drop table(:bpmn_task_candidates)

    drop table(:bpmn_tokens)

    drop_if_exists unique_index(:dmn_definitions, [:organization_id, :key, :version],
                     name: "dmn_definitions_unique_key_version_index"
                   )

    drop_if_exists index(:dmn_definitions, [:organization_id, :key, :status])

    alter table(:dmn_definitions) do
      remove :updated_at
      remove :inserted_at
      remove :content_hash
      remove :errors
      remove :graph
      remove :xml
      remove :status
      remove :version
      remove :name
      remove :key
    end

    drop constraint(:dmn_evaluations, "dmn_evaluations_definition_id_fkey")

    alter table(:dmn_evaluations) do
      modify :definition_id, :uuid
    end

    drop table(:dmn_definitions)

    drop_if_exists index(:dmn_evaluations, [:organization_id, :definition_id])

    drop_if_exists index(:dmn_evaluations, [:organization_id, :correlation_id])

    drop table(:dmn_evaluations)
  end
end
