defmodule AshEnterprise.Repo.Migrations.AddSystemOneBanding do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:system_one_band_table_certifications, primary_key: false) do
      add :organization_id, :uuid, null: false
      add :version_number, :bigint, null: false, default: 1
      add :import_sequence_number, :bigint
      add :overridden_created_on, :utc_datetime_usec
      add :modified_on_behalf_by_id, :uuid
      add :created_on_behalf_by_id, :uuid
      add :modified_by_id, :uuid
      add :created_by_id, :uuid

      add :modified_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :created_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :certified_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :record_version, :text, default: "0"
      add :definition_key, :text, null: false
      add :definition_version, :text, null: false
      add :content_hash, :text, null: false
      add :family, :text, null: false
      add :tenant_scope, :text
      add :calibration_run_id, :uuid
      add :verification, :map
      add :certified_by, :text, null: false
      add :status, :text, null: false, default: "certified"
    end

    create table(:system_one_bandings, primary_key: false) do
      add :organization_id, :uuid, null: false
      add :version_number, :bigint, null: false, default: 1
      add :import_sequence_number, :bigint
      add :overridden_created_on, :utc_datetime_usec
      add :modified_on_behalf_by_id, :uuid
      add :created_on_behalf_by_id, :uuid
      add :modified_by_id, :uuid
      add :created_by_id, :uuid

      add :modified_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :created_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :banded_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :record_version, :text, default: "0"
      add :record_hash, :text
      add :observation_ids, {:array, :uuid}, null: false
      add :band, :text, null: false
      add :fact_value, :text
      add :reason_code, :text
      add :matched_rule_ids, {:array, :text}, null: false
      add :band_table, :map, null: false
      add :decision_evaluation_id, :uuid, null: false
      add :inputs, :map, null: false
      add :mode, :text, null: false, default: "live"
      add :flags, {:array, :text}
      add :correlation_id, :uuid
    end

    create table(:system_one_facts, primary_key: false) do
      add :version_number, :bigint, null: false, default: 1
      add :import_sequence_number, :bigint
      add :overridden_created_on, :utc_datetime_usec
      add :modified_on_behalf_by_id, :uuid
      add :created_on_behalf_by_id, :uuid
      add :modified_by_id, :uuid
      add :created_by_id, :uuid

      add :modified_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :created_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :recorded_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :subject, :map, null: false
      add :subject_type, :text, null: false
      add :subject_id, :text, null: false
      add :predicate, :text, null: false
      add :value, :text, null: false
      add :holds, :boolean, null: false
      add :scope, :map
      add :subject_state_digest, :text
      add :valid_until, :utc_datetime_usec
      add :admission_grade, :text, null: false
      add :admission_id, :uuid
      add :superseded_by, :uuid
    end

    create unique_index(:system_one_facts, [:id], name: "system_one_facts_unique_id_index")
  end

  def down do
    drop_if_exists unique_index(:system_one_facts, [:id],
                     name: "system_one_facts_unique_id_index"
                   )

    drop table(:system_one_facts)

    drop table(:system_one_bandings)

    drop table(:system_one_band_table_certifications)
  end
end
