defmodule AshEnterprise.Repo.Migrations.HumanTaskIsOrganizationOwned do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:bpmn_human_tasks) do
      remove :owning_business_unit_id
      remove :owner_id
      remove :owner_type
      remove :owning_user_id
      remove :owning_team_id
    end
  end

  def down do
    alter table(:bpmn_human_tasks) do
      add :owning_team_id, :uuid
      add :owning_user_id, :uuid
      add :owner_type, :text, null: false, default: "user"
      add :owner_id, :uuid, null: false
      add :owning_business_unit_id, :uuid
    end
  end
end
