defmodule AshEnterprise.Repo.Migrations.AddAgentsDomain do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:agent_messages, primary_key: false) do
      add :organization_id, :uuid, null: false
      add :owning_team_id, :uuid
      add :owning_user_id, :uuid
      add :owner_type, :text, null: false, default: "user"
      add :owner_id, :uuid, null: false
      add :owning_business_unit_id, :uuid
      add :version_number, :bigint, null: false, default: 1
      add :import_sequence_number, :bigint
      add :overridden_created_on, :utc_datetime_usec
      add :modified_on_behalf_by_id, :uuid
      add :created_on_behalf_by_id, :uuid
      add :modified_by_id, :uuid
      add :created_by_id, :uuid

      add :modified_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :created_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :role, :text, null: false
      add :text, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :run_id, :uuid, null: false
    end

    create table(:agent_tool_invocations, primary_key: false) do
      add :organization_id, :uuid, null: false
      add :owning_team_id, :uuid
      add :owning_user_id, :uuid
      add :owner_type, :text, null: false, default: "user"
      add :owner_id, :uuid, null: false
      add :owning_business_unit_id, :uuid
      add :version_number, :bigint, null: false, default: 1
      add :import_sequence_number, :bigint
      add :overridden_created_on, :utc_datetime_usec
      add :modified_on_behalf_by_id, :uuid
      add :created_on_behalf_by_id, :uuid
      add :modified_by_id, :uuid
      add :created_by_id, :uuid

      add :modified_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :created_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :tool_name, :text, null: false
      add :input, :map, null: false, default: %{}
      add :request_id, :text
      add :status, :text, null: false, default: "pending"
      add :result, :map

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :run_id, :uuid, null: false
    end

    create table(:agents_sessions, primary_key: false) do
      add :organization_id, :uuid, null: false
      add :owning_team_id, :uuid
      add :owning_user_id, :uuid
      add :owner_type, :text, null: false, default: "user"
      add :owner_id, :uuid, null: false
      add :owning_business_unit_id, :uuid
      add :version_number, :bigint, null: false, default: 1
      add :import_sequence_number, :bigint
      add :overridden_created_on, :utc_datetime_usec
      add :modified_on_behalf_by_id, :uuid
      add :created_on_behalf_by_id, :uuid
      add :modified_by_id, :uuid
      add :created_by_id, :uuid

      add :modified_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :created_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :title, :text, null: false
      add :status, :text, null: false, default: "active"
      add :workspace_path, :text, null: false
      add :provider, :text, null: false, default: "omp"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:agent_runs, primary_key: false) do
      add :organization_id, :uuid, null: false
      add :owning_team_id, :uuid
      add :owning_user_id, :uuid
      add :owner_type, :text, null: false, default: "user"
      add :owner_id, :uuid, null: false
      add :owning_business_unit_id, :uuid
      add :version_number, :bigint, null: false, default: 1
      add :import_sequence_number, :bigint
      add :overridden_created_on, :utc_datetime_usec
      add :modified_on_behalf_by_id, :uuid
      add :created_on_behalf_by_id, :uuid
      add :modified_by_id, :uuid
      add :created_by_id, :uuid

      add :modified_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :created_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:agent_messages) do
      modify :run_id,
             references(:agent_runs,
               column: :id,
               name: "agent_messages_run_id_fkey",
               type: :uuid,
               prefix: prefix()
             )
    end

    alter table(:agent_tool_invocations) do
      modify :run_id,
             references(:agent_runs,
               column: :id,
               name: "agent_tool_invocations_run_id_fkey",
               type: :uuid,
               prefix: prefix()
             )
    end

    alter table(:agent_runs) do
      add :prompt, :text, null: false
      add :status, :text, null: false, default: "running"
      add :started_at, :utc_datetime_usec, null: false
      add :finished_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :session_id,
          references(:agents_sessions,
            column: :id,
            name: "agent_runs_session_id_fkey",
            type: :uuid,
            prefix: prefix()
          ),
          null: false
    end
  end

  def down do
    drop constraint(:agent_runs, "agent_runs_session_id_fkey")

    alter table(:agent_runs) do
      remove :session_id
      remove :updated_at
      remove :inserted_at
      remove :finished_at
      remove :started_at
      remove :status
      remove :prompt
    end

    drop constraint(:agent_tool_invocations, "agent_tool_invocations_run_id_fkey")

    alter table(:agent_tool_invocations) do
      modify :run_id, :uuid
    end

    drop constraint(:agent_messages, "agent_messages_run_id_fkey")

    alter table(:agent_messages) do
      modify :run_id, :uuid
    end

    drop table(:agent_runs)

    drop table(:agents_sessions)

    drop table(:agent_tool_invocations)

    drop table(:agent_messages)
  end
end
