defmodule AshEnterprise.Repo.Migrations.AddProcessTriggersAndBindings do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:process_triggers, primary_key: false) do
      add :organization_id, :uuid, null: false
      add :version_number, :bigint, null: false, default: 1
      add :import_sequence_number, :bigint
      add :overridden_created_on, :utc_datetime_usec
      add :modified_on_behalf_by_id, :uuid
      add :created_on_behalf_by_id, :uuid
      add :modified_by_id, :uuid
      add :created_by_id, :uuid

      add :modified_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :created_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :key, :text, null: false
      add :version, :bigint, null: false, default: 1
      add :status, :text, null: false, default: "draft"
      add :enabled, :boolean, null: false, default: true
      add :match_resource, :text, null: false
      add :match_action, :text
      add :match_action_type, :text
      add :guard_feel, :text
      add :decision_key, :text
      add :process_key, :text
      add :variable_mapping, :map, null: false, default: %{}
      add :max_starts_per_event, :bigint, null: false, default: 1
    end

    create unique_index(:process_triggers, [:organization_id, :key, :version],
             name: "process_triggers_unique_key_version_index"
           )

    create table(:process_trigger_dispatches, primary_key: false) do
      add :organization_id, :uuid, null: false
      add :version_number, :bigint, null: false, default: 1
      add :import_sequence_number, :bigint
      add :overridden_created_on, :utc_datetime_usec
      add :modified_on_behalf_by_id, :uuid
      add :created_on_behalf_by_id, :uuid
      add :modified_by_id, :uuid
      add :created_by_id, :uuid

      add :modified_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :created_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :event_id, :uuid, null: false
      add :event_sequence, :bigint, null: false
      add :status, :text, null: false
      add :reason, :text
      add :process_key, :text
      add :decision_key, :text
      add :fired_rule, :text
      add :instance_id, :uuid
      add :error, :map
      add :correlation_id, :text
      add :depth, :bigint, null: false, default: 0

      add :trigger_id,
          references(:process_triggers,
            column: :id,
            name: "process_trigger_dispatches_trigger_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:process_trigger_dispatches, [:organization_id, :trigger_id, :event_id],
             name: "process_trigger_dispatches_once_per_event_index"
           )

    create table(:process_trigger_cursors, primary_key: false) do
      add :organization_id, :uuid, null: false
      add :version_number, :bigint, null: false, default: 1
      add :import_sequence_number, :bigint
      add :overridden_created_on, :utc_datetime_usec
      add :modified_on_behalf_by_id, :uuid
      add :created_on_behalf_by_id, :uuid
      add :modified_by_id, :uuid
      add :created_by_id, :uuid

      add :modified_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :created_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :last_sequence, :bigint, null: false, default: 0
      add :last_dispatched_at, :utc_datetime_usec
    end

    create unique_index(:process_trigger_cursors, [:organization_id],
             name: "process_trigger_cursors_one_per_tenant_index"
           )

    create table(:process_bindings, primary_key: false) do
      add :organization_id, :uuid, null: false
      add :version_number, :bigint, null: false, default: 1
      add :import_sequence_number, :bigint
      add :overridden_created_on, :utc_datetime_usec
      add :modified_on_behalf_by_id, :uuid
      add :created_on_behalf_by_id, :uuid
      add :modified_by_id, :uuid
      add :created_by_id, :uuid

      add :modified_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :created_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :kind, :text, null: false
      add :key, :text, null: false
      add :source, :text, null: false
      add :target_id, :uuid, null: false
      add :bound_version, :bigint, null: false
      add :forked_from_version, :bigint

      add :bound_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :bound_by_id, :uuid
    end

    create unique_index(:process_bindings, [:organization_id, :kind, :key],
             name: "process_bindings_one_per_key_index"
           )
  end

  def down do
    drop_if_exists unique_index(:process_bindings, [:organization_id, :kind, :key],
                     name: "process_bindings_one_per_key_index"
                   )

    drop table(:process_bindings)

    drop_if_exists unique_index(:process_trigger_cursors, [:organization_id],
                     name: "process_trigger_cursors_one_per_tenant_index"
                   )

    drop table(:process_trigger_cursors)

    drop constraint(:process_trigger_dispatches, "process_trigger_dispatches_trigger_id_fkey")

    drop_if_exists unique_index(
                     :process_trigger_dispatches,
                     [:organization_id, :trigger_id, :event_id],
                     name: "process_trigger_dispatches_once_per_event_index"
                   )

    drop table(:process_trigger_dispatches)

    drop_if_exists unique_index(:process_triggers, [:organization_id, :key, :version],
                     name: "process_triggers_unique_key_version_index"
                   )

    drop table(:process_triggers)
  end
end
