defmodule AshEnterprise.Repo.Migrations.AddLegacyUserReadModel do
  @moduledoc """
  Strangler compatibility layer, generated by `mix ash_strangler.gen.migration`.

  Covers: AshEnterprise.Legacy.User

  Regenerate rather than hand-editing. Every statement is idempotent
  (`CREATE OR REPLACE`, `IF NOT EXISTS`), so re-running this after a mapping
  change is safe.
  """

  use Ecto.Migration

  def up do
    execute("""
    CREATE SCHEMA IF NOT EXISTS "strangler";
    """)

    execute("""
    CREATE OR REPLACE VIEW "strangler"."users" AS
    SELECT
      uuid_generate_v5('ce41843a-c056-4c3e-9c79-50e7e5f4887c'::uuid, 'legacy.users:' || id::text) AS id,
      id AS __legacy_id,
      ('00000000-0000-0000-0000-0000000000fe')::uuid AS organization_id,
      ('00000000-0000-0000-0000-0000000000fd')::uuid AS owning_business_unit_id,
      (CASE WHEN (state = 'active') THEN ('active')::text ELSE ('inactive')::text END) AS lifecycle_status,
      1 AS version_number,
      NULL AS import_sequence_number,
      NULL AS overridden_created_on,
      NULL AS modified_on_behalf_by_id,
      NULL AS created_on_behalf_by_id,
      NULL AS modified_by_id,
      NULL AS created_by_id,
      (updated_at AT TIME ZONE 'UTC') AS modified_on,
      (created_at AT TIME ZONE 'UTC') AS created_on,
      id AS legacy_id,
      login AS login,
      (email)::citext AS email,
      (coalesce(first_name, '') || (' ' || coalesce(last_name, ''))) AS full_name,
      (state)::text AS legacy_state,
      (deleted_at AT TIME ZONE 'UTC') AS archived_at
    FROM legacy.users;
    """)

    execute("""
    CREATE INDEX IF NOT EXISTS strangler_users_key_idx ON legacy.users
      (uuid_generate_v5('ce41843a-c056-4c3e-9c79-50e7e5f4887c'::uuid, 'legacy.users:' || id::text));
    """)

    execute("""
    CREATE OR REPLACE FUNCTION "strangler"."strangler_users_notify"() RETURNS trigger AS $strangler$
    DECLARE
      affected record;
    BEGIN
      affected := COALESCE(NEW, OLD);

      -- Key only. See the moduledoc: a payload built from row data can exceed
      -- the 7999-byte ceiling and abort the LEGACY application's transaction.
      PERFORM pg_notify('ash_strangler', json_build_object(
        'resource', 'Elixir.AshEnterprise.Legacy.User',
        'legacy_id', affected.id,
        'op', lower(TG_OP)
      )::text);

      -- The return value of an AFTER row trigger is ignored.
      RETURN NULL;
    END $strangler$ LANGUAGE plpgsql;
    """)

    execute("""
    CREATE OR REPLACE TRIGGER "strangler_users_notify"
      AFTER INSERT OR UPDATE OR DELETE ON legacy.users
      FOR EACH ROW EXECUTE FUNCTION "strangler"."strangler_users_notify"();
    """)
  end

  def down do
    execute("""
    DO $strangler$
    BEGIN
      IF to_regclass('legacy.users') IS NOT NULL THEN
        EXECUTE 'DROP TRIGGER IF EXISTS "strangler_users_notify" ON legacy.users';
      END IF;
    END $strangler$;
    """)

    execute("""
    DROP FUNCTION IF EXISTS "strangler"."strangler_users_notify"() CASCADE;
    """)

    execute("""
    DROP INDEX IF EXISTS legacy.strangler_users_key_idx;
    """)

    execute("""
    DROP VIEW IF EXISTS "strangler"."users";
    """)

    execute("""
    DO $strangler$
    BEGIN
      IF NOT EXISTS (
        SELECT 1
          FROM pg_class c
          JOIN pg_namespace n ON n.oid = c.relnamespace
         WHERE n.nspname = 'strangler'
      ) AND NOT EXISTS (
        SELECT 1
          FROM pg_proc p
          JOIN pg_namespace n ON n.oid = p.pronamespace
         WHERE n.nspname = 'strangler'
      ) THEN
        EXECUTE 'DROP SCHEMA IF EXISTS "strangler"';
      END IF;
    END $strangler$;
    """)
  end
end
