defmodule AshEnterprise.Repo.Migrations.TamperEvidentAuditLog do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:audit_events) do
      add :sequence, :bigserial
      add :organization_id, :uuid
      add :previous_hash, :text
      add :hash, :text
    end

    create index(:audit_events, [:organization_id, :sequence], name: "audit_events_chain_index")

    execute("""
    CREATE OR REPLACE FUNCTION ash_enterprise_audit_chain() RETURNS trigger AS $fn$
    DECLARE
      prev text;
    BEGIN
      -- The tenant is taken from the metadata the platform stamps rather than
      -- accepted from the caller, so the column and the metadata cannot
      -- disagree. See AshEnterprise.Platform.Changes.StampCorrelation.
      NEW.organization_id := NULLIF(NEW.metadata->>'organization_id', '')::uuid;

      SELECT hash INTO prev
      FROM audit_events
      WHERE organization_id IS NOT DISTINCT FROM NEW.organization_id
      ORDER BY sequence DESC
      LIMIT 1;

      NEW.previous_hash := prev;
      NEW.hash := encode(sha256(convert_to(concat_ws('|',
        coalesce(prev, ''),
        NEW.sequence::text,
        NEW.id::text,
        NEW.record_id::text,
        NEW.version::text,
        NEW.occurred_at::text,
        NEW.resource,
        NEW.action,
        NEW.action_type,
        coalesce(NEW.user_id::text, ''),
        coalesce(NEW.organization_id::text, ''),
        NEW.data::text,
        NEW.changed_attributes::text,
        NEW.metadata::text
      ), 'UTF8')), 'hex');

      RETURN NEW;
    END;
    $fn$ LANGUAGE plpgsql;
    """)

    execute("""
    CREATE TRIGGER audit_events_chain
      BEFORE INSERT ON audit_events
      FOR EACH ROW EXECUTE FUNCTION ash_enterprise_audit_chain();
    """)

    execute("""
    CREATE OR REPLACE FUNCTION ash_enterprise_audit_immutable() RETURNS trigger AS $fn$
    BEGIN
      RAISE EXCEPTION 'audit_events is append-only; % is not permitted', TG_OP
        USING ERRCODE = 'restrict_violation',
              HINT = 'Correct a wrong entry by recording a new one.';
    END;
    $fn$ LANGUAGE plpgsql;
    """)

    execute("""
    CREATE TRIGGER audit_events_immutable
      BEFORE UPDATE OR DELETE ON audit_events
      FOR EACH ROW EXECUTE FUNCTION ash_enterprise_audit_immutable();
    """)
  end

  def down do
    execute("""
    DROP TRIGGER IF EXISTS audit_events_immutable ON audit_events;
    """)

    execute("""
    DROP FUNCTION IF EXISTS ash_enterprise_audit_immutable() CASCADE;
    """)

    execute("""
    DROP TRIGGER IF EXISTS audit_events_chain ON audit_events;
    """)

    execute("""
    DROP FUNCTION IF EXISTS ash_enterprise_audit_chain() CASCADE;
    """)

    drop_if_exists index(:audit_events, [:organization_id, :sequence],
                     name: "audit_events_chain_index"
                   )

    alter table(:audit_events) do
      remove :hash
      remove :previous_hash
      remove :organization_id
      remove :sequence
    end
  end
end
