defmodule AshEnterprise.Repo.Migrations.AddHierarchySecurity do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :manager_id,
          references(:users,
            column: :id,
            name: "users_manager_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :position_id, :uuid
    end

    create table(:positions, primary_key: false) do
      add :organization_id, :uuid, null: false
      add :status_code, :bigint
      add :state_code, :bigint, null: false, default: 0
      add :version_number, :bigint, null: false, default: 1
      add :import_sequence_number, :bigint
      add :overridden_created_on, :utc_datetime_usec
      add :modified_on_behalf_by_id, :uuid
      add :created_on_behalf_by_id, :uuid
      add :modified_by_id, :uuid
      add :created_by_id, :uuid

      add :modified_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :created_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:users) do
      modify :position_id,
             references(:positions,
               column: :id,
               name: "users_position_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:positions) do
      add :name, :text, null: false
      add :description, :text

      add :parent_position_id,
          references(:positions,
            column: :id,
            name: "positions_parent_position_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          )

      add :archived_at, :utc_datetime_usec
    end

    create unique_index(:positions, [:organization_id, :name],
             name: "positions_unique_name_index"
           )
  end

  def down do
    drop_if_exists unique_index(:positions, [:organization_id, :name],
                     name: "positions_unique_name_index"
                   )

    drop constraint(:positions, "positions_parent_position_id_fkey")

    alter table(:positions) do
      remove :archived_at
      remove :parent_position_id
      remove :description
      remove :name
    end

    drop constraint(:users, "users_position_id_fkey")

    alter table(:users) do
      modify :position_id, :uuid
    end

    drop table(:positions)

    drop constraint(:users, "users_manager_id_fkey")

    alter table(:users) do
      remove :position_id
      remove :manager_id
    end
  end
end
