defmodule AshEnterprise.Repo.Migrations.AdoptFirstPartyPackageMains do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:dmn_evaluations) do
      modify :decision_id, :text, null: true
    end

    alter table(:dmn_definitions) do
      add :verification, :map
    end

    alter table(:bpmn_instances) do
      add :superseded_by_instance_id, :uuid
      add :superseded_at, :utc_datetime_usec
    end

    create index(:bpmn_instances, [:organization_id, :superseded_by_instance_id],
             name: "bpmn_instances_superseded_by_index",
             where: "superseded_by_instance_id IS NOT NULL"
           )
  end

  def down do
    drop_if_exists index(:bpmn_instances, [:organization_id, :superseded_by_instance_id],
                     name: "bpmn_instances_superseded_by_index"
                   )

    alter table(:bpmn_instances) do
      remove :superseded_at
      remove :superseded_by_instance_id
    end

    alter table(:dmn_definitions) do
      remove :verification
    end

    alter table(:dmn_evaluations) do
      modify :decision_id, :text, null: false
    end
  end
end
