defmodule AshEnterprise.Repo.Migrations.AdoptTriggerEngine do
  @moduledoc """
  Adopts the ash_bpmn trigger engine: creates its `Subscription`, `Cursor` and
  `Dispatch` tables on the platform base, and **drops the prototype's** —
  replacement, not migration (TRD §10).

  No production system ever ran the prototype. Its modules are deleted in the
  same change, its data is not carried over, and development databases re-seed
  rather than migrate. The drop is here so one change is the whole cutover:
  there is never a moment when both sweeps could run against a tenant, and
  therefore no lock-name handoff to coordinate.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  (the three `bpmn_*` tables and their indexes); the `process_trigger_*` drops
  were appended by hand, children before parents for the foreign key.
  """

  use Ecto.Migration

  def up do
    create table(:bpmn_subscriptions, primary_key: false) do
      add :organization_id, :uuid, null: false
      add :version_number, :bigint, null: false, default: 1
      add :import_sequence_number, :bigint
      add :overridden_created_on, :utc_datetime_usec
      add :modified_on_behalf_by_id, :uuid
      add :created_on_behalf_by_id, :uuid
      add :modified_by_id, :uuid
      add :created_by_id, :uuid

      add :modified_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :created_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :key, :text, null: false
      add :version, :bigint, null: false
      add :status, :text, null: false, default: "draft"
      add :enabled, :boolean, null: false, default: true
      add :source, :text, null: false, default: "standalone"
      add :definition_id, :uuid
      add :node_id, :text
      add :match_resource, :text, null: false
      add :match_action, :text
      add :match_action_type, :text
      add :kind, :text, null: false, default: "message"
      add :signal_name, :text
      add :guard_feel, :text
      add :subject_of, :text, null: false, default: "event.record_id"
      add :correlation_key_feel, :text
      add :route_kind, :text, null: false, default: "static"
      add :process_key, :text
      add :decision_key, :text
      add :variable_mapping, :map, null: false, default: %{}
      add :max_starts_per_event, :bigint, null: false, default: 1
      add :lookback_minutes, :bigint, null: false, default: 0
      add :compiled, :map

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:bpmn_subscriptions, [:organization_id, :match_resource])

    create index(:bpmn_subscriptions, [:organization_id, :key, :status],
             unique: true,
             where: "status = 'draft'"
           )

    create unique_index(:bpmn_subscriptions, [:organization_id, :key, :version],
             name: "bpmn_subscriptions_unique_key_version_index"
           )

    create table(:bpmn_dispatches, primary_key: false) do
      add :organization_id, :uuid, null: false
      add :version_number, :bigint, null: false, default: 1
      add :import_sequence_number, :bigint
      add :overridden_created_on, :utc_datetime_usec
      add :modified_on_behalf_by_id, :uuid
      add :created_on_behalf_by_id, :uuid
      add :modified_by_id, :uuid
      add :created_by_id, :uuid

      add :modified_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :created_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :subscription_id,
          references(:bpmn_subscriptions,
            column: :id,
            name: "bpmn_dispatches_subscription_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :waiting_token_id,
          references(:bpmn_tokens,
            column: :id,
            name: "bpmn_dispatches_waiting_token_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :event_id, :uuid, null: false
      add :event_sequence, :bigint, null: false
      add :event_occurred_at, :utc_datetime_usec, null: false
      add :kind, :text, null: false
      add :status, :text, null: false
      add :reason, :text
      add :process_key, :text
      add :instance_id, :uuid
      add :decision_key, :text
      add :fired_rule, :text
      add :correlation_id, :text
      add :depth, :bigint, null: false, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:bpmn_dispatches, [:organization_id, :event_sequence])

    create index(:bpmn_dispatches, [:organization_id, :waiting_token_id, :event_id],
             unique: true,
             where: "waiting_token_id IS NOT NULL"
           )

    create index(:bpmn_dispatches, [:organization_id, :subscription_id, :event_id],
             unique: true,
             where: "subscription_id IS NOT NULL"
           )

    create table(:bpmn_cursors, primary_key: false) do
      add :organization_id, :uuid, null: false
      add :version_number, :bigint, null: false, default: 1
      add :import_sequence_number, :bigint
      add :overridden_created_on, :utc_datetime_usec
      add :modified_on_behalf_by_id, :uuid
      add :created_on_behalf_by_id, :uuid
      add :modified_by_id, :uuid
      add :created_by_id, :uuid

      add :modified_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :created_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :last_sequence, :bigint, null: false, default: 0
      add :last_dispatched_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:bpmn_cursors, [:organization_id],
             name: "bpmn_cursors_one_per_tenant_index"
           )

    # ── Replacement, not migration ─────────────────────────────────────────
    #
    # The prototype's tables, dropped in the same change that brings their
    # successors. Dispatches before the trigger table, for the foreign key.
    drop table(:process_trigger_dispatches)
    drop table(:process_trigger_cursors)
    drop table(:process_triggers)
  end

  def down do
    drop_if_exists unique_index(:bpmn_cursors, [:organization_id],
                     name: "bpmn_cursors_one_per_tenant_index"
                   )

    drop table(:bpmn_cursors)

    drop constraint(:bpmn_dispatches, "bpmn_dispatches_subscription_id_fkey")

    drop constraint(:bpmn_dispatches, "bpmn_dispatches_waiting_token_id_fkey")

    drop_if_exists index(:bpmn_dispatches, [:organization_id, :subscription_id, :event_id])

    drop_if_exists index(:bpmn_dispatches, [:organization_id, :waiting_token_id, :event_id])

    drop_if_exists index(:bpmn_dispatches, [:organization_id, :event_sequence])

    drop table(:bpmn_dispatches)

    drop_if_exists unique_index(:bpmn_subscriptions, [:organization_id, :key, :version],
                     name: "bpmn_subscriptions_unique_key_version_index"
                   )

    drop_if_exists index(:bpmn_subscriptions, [:organization_id, :key, :status])

    drop_if_exists index(:bpmn_subscriptions, [:organization_id, :match_resource])

    drop table(:bpmn_subscriptions)

    # The prototype's tables are deliberately not rebuilt: replacement, not
    # migration. A rolled-back dev database re-seeds instead.
  end
end
