defmodule AshEnterprise.Repo.Migrations.AddSystemOneCalibration do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:system_one_calibration_samples, primary_key: false) do
      add :organization_id, :uuid, null: false
      add :version_number, :bigint, null: false, default: 1
      add :import_sequence_number, :bigint
      add :overridden_created_on, :utc_datetime_usec
      add :modified_on_behalf_by_id, :uuid
      add :created_on_behalf_by_id, :uuid
      add :modified_by_id, :uuid
      add :created_by_id, :uuid

      add :modified_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :created_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :added_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :record_version, :text, default: "0"
      add :family, :text, null: false
      add :question_hash, :text, null: false
      add :model_digest, :text, null: false
      add :runtime_version, :text, null: false
      add :region, :text, null: false
      add :tenant, :text
      add :observation_id, :uuid, null: false
      add :pair_digest, :text, null: false
      add :gold_label_digest, :text
    end

    create unique_index(
             :system_one_calibration_samples,
             [:organization_id, :observation_id, :question_hash, :model_digest, :region],
             name: "system_one_calibration_samples_unique_observation_index"
           )

    create table(:system_one_calibration_runs, primary_key: false) do
      add :organization_id, :uuid, null: false
      add :version_number, :bigint, null: false, default: 1
      add :import_sequence_number, :bigint
      add :overridden_created_on, :utc_datetime_usec
      add :modified_on_behalf_by_id, :uuid
      add :created_on_behalf_by_id, :uuid
      add :modified_by_id, :uuid
      add :created_by_id, :uuid

      add :modified_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :created_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :started_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :record_version, :text, default: "0"
      add :record_hash, :text
      add :family, :text, null: false
      add :question_hashes, {:array, :text}, null: false
      add :model_version, :text, null: false
      add :model_digest, :text, null: false
      add :runtime_version, :text, null: false
      add :eval_set_hash, :text, null: false
      add :region, :text, null: false
      add :tenant, :text
      add :risk_tier, :text
      add :n, :bigint, null: false
      add :n_per_class, :map, default: %{}
      add :metrics, :map, null: false
      add :ece, :text
      add :brier, :text
      add :conformal_thresholds, :map, default: %{}
      add :source, :text, null: false
      add :created_by, :text
      add :observations_digest, :text
      add :result, :text, null: false
      add :proposed_band_table, :map
      add :pass_bar, :map, default: %{}
      add :finished_at, :utc_datetime_usec
    end

    create unique_index(:system_one_calibration_runs, [:organization_id, :id],
             name: "system_one_calibration_runs_unique_id_index"
           )
  end

  def down do
    drop_if_exists unique_index(:system_one_calibration_runs, [:organization_id, :id],
                     name: "system_one_calibration_runs_unique_id_index"
                   )

    drop table(:system_one_calibration_runs)

    drop_if_exists unique_index(
                     :system_one_calibration_samples,
                     [:organization_id, :observation_id, :question_hash, :model_digest, :region],
                     name: "system_one_calibration_samples_unique_observation_index"
                   )

    drop table(:system_one_calibration_samples)
  end
end
