defmodule AshEnterprise.Repo.Migrations.AddSubProcessorOptIn do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:organizations) do
      add :sub_processor_opt_in, :boolean, null: false, default: false
    end
  end

  def down do
    alter table(:organizations) do
      remove :sub_processor_opt_in
    end
  end
end
