defmodule AshEnterprise.Repo.Migrations.AddComplianceControlPlane do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:ash_compliance_control_mappings, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :organization_id, :uuid
      add :gap, :text, null: false
      add :control_id, :text, null: false
      add :profile_revision_id, :uuid
      add :jurisdiction, :text
      add :notes, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:ash_compliance_control_mappings, [:organization_id, :gap],
             name: "ash_compliance_control_mappings_unique_gap_per_org_index"
           )

    create table(:ash_compliance_policy_bundles, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :organization_id, :uuid, null: false
      add :label, :text
      add :rules_json, :text, null: false
      add :content_hash, :text, null: false
      add :manifest_revision, :text, null: false
      add :compiler_version, :text, null: false
      add :contributions, {:array, :map}, default: []
      add :status, :text, null: false, default: "compiled"
      add :active_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:ash_compliance_policy_bundles, [:organization_id, :content_hash],
             name: "ash_compliance_policy_bundles_unique_hash_per_org_index"
           )

    create table(:ash_compliance_profile_revisions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :profile_id, :uuid, null: false
      add :version, :text, null: false
      add :source, :text
      add :operations, {:array, :map}, default: []
      add :content_hash, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:ash_compliance_profile_revisions, [:profile_id, :version],
             name: "ash_compliance_profile_revisions_unique_revision_index"
           )

    create table(:ash_compliance_tenant_policy_sets, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :organization_id, :uuid, null: false
      add :name, :text
      add :profile_revision_ids, {:array, :uuid}, default: []
      add :rule_set_revision_ids, {:array, :uuid}, default: []
      add :active_policy_bundle_id, :uuid

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:ash_compliance_tenant_policy_sets, [:organization_id],
             name: "ash_compliance_tenant_policy_sets_one_per_organization_index"
           )

    create table(:ash_compliance_evidence_artifacts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :organization_id, :uuid, null: false
      add :control_id, :text, null: false
      add :subject_type, :text
      add :subject_id, :text
      add :hash, :text, null: false
      add :media_type, :text, null: false
      add :collector, :text, null: false
      add :method, :text, null: false
      add :chain_of_custody, {:array, :map}, default: []
      add :retention_class, :text
      add :collected_at, :utc_datetime_usec, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:ash_compliance_compliance_evaluations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :organization_id, :uuid, null: false
      add :control_id, :text
      add :subject_type, :text
      add :subject_id, :text
      add :bundle_hash, :text, null: false
      add :bundle_revision, :text
      add :evaluator, :text, null: false
      add :compiler_version, :text
      add :outcome, :text, null: false
      add :fact_snapshot_hash, :text, null: false
      add :missing_facts, {:array, :text}, default: []
      add :rule_ids, {:array, :text}, default: []
      add :correlation_id, :text
      add :source_event_id, :text
      add :evaluated_at, :utc_datetime_usec, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:ash_compliance_catalogs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :organization_id, :uuid
      add :name, :text, null: false
      add :description, :text
      add :oscal_uuid, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:ash_compliance_catalogs, [:organization_id, :name],
             name: "ash_compliance_catalogs_unique_name_per_org_index"
           )

    create table(:ash_compliance_profiles, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :organization_id, :uuid
      add :catalog_id, :uuid
      add :name, :text, null: false
      add :oscal_uuid, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:ash_compliance_profiles, [:organization_id, :name],
             name: "ash_compliance_profiles_unique_name_per_org_index"
           )

    create table(:ash_compliance_controls, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :organization_id, :uuid
      add :catalog_id, :uuid
      add :control_id, :text, null: false
      add :title, :text
      add :family, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:ash_compliance_controls, [:organization_id, :control_id],
             name: "ash_compliance_controls_unique_control_id_index"
           )

    create table(:ash_compliance_findings, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :organization_id, :uuid, null: false
      add :control_id, :text, null: false
      add :subject_type, :text, null: false
      add :subject_id, :text, null: false
      add :status, :text, null: false, default: "unknown"
      add :severity, :text
      add :gap, :text
      add :breach_count, :bigint, null: false, default: 0
      add :first_seen_at, :utc_datetime_usec
      add :last_seen_at, :utc_datetime_usec
      add :resolved_at, :utc_datetime_usec
      add :explanation, :text
      add :bundle_hash, :text
      add :rule_ids, {:array, :text}, default: []

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(
             :ash_compliance_findings,
             [:organization_id, :control_id, :subject_type, :subject_id],
             name: "ash_compliance_findings_by_grain_index"
           )

    create table(:compliance_events, primary_key: false) do
      add :organization_id, :uuid
      add :practice_id, :uuid
      add :user_id, :uuid
      add :id, :bigserial, null: false, primary_key: true
      add :record_id, :uuid, null: false
      add :version, :bigint, null: false, default: 1
      add :metadata, :map, null: false, default: %{}
      add :data, :map, null: false, default: %{}
      add :changed_attributes, :map, null: false, default: %{}
      add :occurred_at, :utc_datetime_usec, null: false
      add :resource, :text, null: false
      add :action, :text, null: false
      add :action_type, :text, null: false
    end

    create table(:ash_compliance_control_revisions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :control_id, :uuid, null: false
      add :version, :text, null: false
      add :statement, :text
      add :params, {:array, :map}, default: []
      add :citations, {:array, :text}, default: []
      add :status, :text, null: false, default: "draft"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:ash_compliance_control_revisions, [:control_id, :version],
             name: "ash_compliance_control_revisions_unique_revision_index"
           )

    create table(:ash_compliance_rule_set_revisions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :organization_id, :uuid
      add :name, :text, null: false
      add :revision, :text, null: false, default: "1"
      add :layer, :text, null: false
      add :combining, :text, null: false, default: "deny_overrides"
      add :source_module, :text
      add :rules_json, :text, null: false
      add :content_hash, :text, null: false
      add :status, :text, null: false, default: "draft"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:ash_compliance_rule_set_revisions, [:organization_id, :name, :revision],
             name: "ash_compliance_rule_set_revisions_unique_revision_index"
           )

    create table(:ash_compliance_catalog_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :catalog_id, :uuid, null: false
      add :version, :text, null: false
      add :source, :text
      add :content_hash, :text, null: false
      add :published_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:ash_compliance_catalog_versions, [:catalog_id, :content_hash],
             name: "ash_compliance_catalog_versions_unique_hash_index"
           )

    create unique_index(:ash_compliance_catalog_versions, [:catalog_id, :version],
             name: "ash_compliance_catalog_versions_unique_version_index"
           )

    create table(:ash_compliance_policy_overrides, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :organization_id, :uuid, null: false
      add :kind, :text, null: false
      add :rule_id, :text, null: false
      add :reason, :text, null: false
      add :approver, :text, null: false
      add :approved_at, :utc_datetime_usec, null: false
      add :starts_at, :utc_datetime_usec
      add :expires_at, :utc_datetime_usec
      add :scope_subject_type, :text
      add :scope_subject_id, :text
      add :compensating_controls, {:array, :text}, default: []
      add :replacement_rules_json, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop table(:ash_compliance_policy_overrides)

    drop_if_exists unique_index(:ash_compliance_catalog_versions, [:catalog_id, :version],
                     name: "ash_compliance_catalog_versions_unique_version_index"
                   )

    drop_if_exists unique_index(:ash_compliance_catalog_versions, [:catalog_id, :content_hash],
                     name: "ash_compliance_catalog_versions_unique_hash_index"
                   )

    drop table(:ash_compliance_catalog_versions)

    drop_if_exists unique_index(
                     :ash_compliance_rule_set_revisions,
                     [:organization_id, :name, :revision],
                     name: "ash_compliance_rule_set_revisions_unique_revision_index"
                   )

    drop table(:ash_compliance_rule_set_revisions)

    drop_if_exists unique_index(:ash_compliance_control_revisions, [:control_id, :version],
                     name: "ash_compliance_control_revisions_unique_revision_index"
                   )

    drop table(:ash_compliance_control_revisions)

    drop table(:compliance_events)

    drop_if_exists unique_index(
                     :ash_compliance_findings,
                     [:organization_id, :control_id, :subject_type, :subject_id],
                     name: "ash_compliance_findings_by_grain_index"
                   )

    drop table(:ash_compliance_findings)

    drop_if_exists unique_index(:ash_compliance_controls, [:organization_id, :control_id],
                     name: "ash_compliance_controls_unique_control_id_index"
                   )

    drop table(:ash_compliance_controls)

    drop_if_exists unique_index(:ash_compliance_profiles, [:organization_id, :name],
                     name: "ash_compliance_profiles_unique_name_per_org_index"
                   )

    drop table(:ash_compliance_profiles)

    drop_if_exists unique_index(:ash_compliance_catalogs, [:organization_id, :name],
                     name: "ash_compliance_catalogs_unique_name_per_org_index"
                   )

    drop table(:ash_compliance_catalogs)

    drop table(:ash_compliance_compliance_evaluations)

    drop table(:ash_compliance_evidence_artifacts)

    drop_if_exists unique_index(:ash_compliance_tenant_policy_sets, [:organization_id],
                     name: "ash_compliance_tenant_policy_sets_one_per_organization_index"
                   )

    drop table(:ash_compliance_tenant_policy_sets)

    drop_if_exists unique_index(:ash_compliance_profile_revisions, [:profile_id, :version],
                     name: "ash_compliance_profile_revisions_unique_revision_index"
                   )

    drop table(:ash_compliance_profile_revisions)

    drop_if_exists unique_index(:ash_compliance_policy_bundles, [:organization_id, :content_hash],
                     name: "ash_compliance_policy_bundles_unique_hash_per_org_index"
                   )

    drop table(:ash_compliance_policy_bundles)

    drop_if_exists unique_index(:ash_compliance_control_mappings, [:organization_id, :gap],
                     name: "ash_compliance_control_mappings_unique_gap_per_org_index"
                   )

    drop table(:ash_compliance_control_mappings)
  end
end
