defmodule AshEnterprise.Repo.Migrations.AddCanonicalDomain do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:canonical_accounts, primary_key: false) do
      add :organization_id, :uuid, null: false
      add :version_number, :bigint, null: false, default: 1
      add :import_sequence_number, :bigint
      add :overridden_created_on, :utc_datetime_usec
      add :modified_on_behalf_by_id, :uuid
      add :created_on_behalf_by_id, :uuid
      add :modified_by_id, :uuid
      add :created_by_id, :uuid

      add :modified_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :created_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :provider, :text, null: false
      add :external_id, :text, null: false
      add :display_name, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:canonical_accounts, [:organization_id, :provider, :external_id],
             name: "canonical_accounts_unique_provider_account_index"
           )

    create table(:canonical_people, primary_key: false) do
      add :organization_id, :uuid, null: false
      add :owning_team_id, :uuid
      add :owning_user_id, :uuid
      add :owner_type, :text, null: false, default: "user"
      add :owner_id, :uuid, null: false
      add :owning_business_unit_id, :uuid
      add :version_number, :bigint, null: false, default: 1
      add :import_sequence_number, :bigint
      add :overridden_created_on, :utc_datetime_usec
      add :modified_on_behalf_by_id, :uuid
      add :created_on_behalf_by_id, :uuid
      add :modified_by_id, :uuid
      add :created_by_id, :uuid

      add :modified_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :created_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text
      add :email, :citext

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:canonical_people, [:organization_id, :email],
             name: "canonical_people_unique_email_index"
           )

    create table(:canonical_conversations, primary_key: false) do
      add :organization_id, :uuid, null: false
      add :version_number, :bigint, null: false, default: 1
      add :import_sequence_number, :bigint
      add :overridden_created_on, :utc_datetime_usec
      add :modified_on_behalf_by_id, :uuid
      add :created_on_behalf_by_id, :uuid
      add :modified_by_id, :uuid
      add :created_by_id, :uuid

      add :modified_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :created_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :subject, :text
      add :participants, :map, default: %{}
      add :external_system, :text
      add :external_id, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(
             :canonical_conversations,
             [:organization_id, :external_system, :external_id],
             name: "canonical_conversations_unique_external_index"
           )

    create table(:canonical_projects, primary_key: false) do
      add :organization_id, :uuid, null: false
      add :version_number, :bigint, null: false, default: 1
      add :import_sequence_number, :bigint
      add :overridden_created_on, :utc_datetime_usec
      add :modified_on_behalf_by_id, :uuid
      add :created_on_behalf_by_id, :uuid
      add :modified_by_id, :uuid
      add :created_by_id, :uuid

      add :modified_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :created_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :external_system, :text
      add :external_id, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:canonical_projects, [:organization_id, :external_system, :external_id],
             name: "canonical_projects_unique_external_index"
           )

    create table(:canonical_messages, primary_key: false) do
      add :organization_id, :uuid, null: false
      add :owning_team_id, :uuid
      add :owning_user_id, :uuid
      add :owner_type, :text, null: false, default: "user"
      add :owner_id, :uuid, null: false
      add :owning_business_unit_id, :uuid
      add :version_number, :bigint, null: false, default: 1
      add :import_sequence_number, :bigint
      add :overridden_created_on, :utc_datetime_usec
      add :modified_on_behalf_by_id, :uuid
      add :created_on_behalf_by_id, :uuid
      add :modified_by_id, :uuid
      add :created_by_id, :uuid

      add :modified_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :created_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :body, :text
      add :sent_at, :utc_datetime_usec, null: false
      add :direction, :text, null: false
      add :external_system, :text
      add :external_id, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :conversation_id,
          references(:canonical_conversations,
            column: :id,
            name: "canonical_messages_conversation_id_fkey",
            type: :uuid,
            prefix: prefix()
          )
    end

    create unique_index(:canonical_messages, [:organization_id, :external_system, :external_id],
             name: "canonical_messages_unique_external_index"
           )

    alter table(:canonical_messages) do
      add :sender_id,
          references(:canonical_people,
            column: :id,
            name: "canonical_messages_sender_id_fkey",
            type: :uuid,
            prefix: prefix()
          )
    end

    create table(:canonical_tasks, primary_key: false) do
      add :organization_id, :uuid, null: false
      add :owning_team_id, :uuid
      add :owning_user_id, :uuid
      add :owner_type, :text, null: false, default: "user"
      add :owner_id, :uuid, null: false
      add :owning_business_unit_id, :uuid
      add :version_number, :bigint, null: false, default: 1
      add :import_sequence_number, :bigint
      add :overridden_created_on, :utc_datetime_usec
      add :modified_on_behalf_by_id, :uuid
      add :created_on_behalf_by_id, :uuid
      add :modified_by_id, :uuid
      add :created_by_id, :uuid

      add :modified_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :created_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :title, :text, null: false
      add :due_at, :utc_datetime_usec
      add :status, :text, null: false, default: "open"
      add :source, :text, null: false
      add :external_system, :text
      add :external_id, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:canonical_tasks, [:organization_id, :external_system, :external_id],
             name: "canonical_tasks_unique_external_index"
           )

    create table(:canonical_calendar_events, primary_key: false) do
      add :organization_id, :uuid, null: false
      add :owning_team_id, :uuid
      add :owning_user_id, :uuid
      add :owner_type, :text, null: false, default: "user"
      add :owner_id, :uuid, null: false
      add :owning_business_unit_id, :uuid
      add :version_number, :bigint, null: false, default: 1
      add :import_sequence_number, :bigint
      add :overridden_created_on, :utc_datetime_usec
      add :modified_on_behalf_by_id, :uuid
      add :created_on_behalf_by_id, :uuid
      add :modified_by_id, :uuid
      add :created_by_id, :uuid

      add :modified_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :created_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :title, :text, null: false
      add :starts_at, :utc_datetime_usec, null: false
      add :ends_at, :utc_datetime_usec, null: false
      add :location, :text
      add :external_uid, :text
      add :external_system, :text
      add :external_id, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organizer_id,
          references(:canonical_people,
            column: :id,
            name: "canonical_calendar_events_organizer_id_fkey",
            type: :uuid,
            prefix: prefix()
          )
    end

    create unique_index(
             :canonical_calendar_events,
             [:organization_id, :external_system, :external_id],
             name: "canonical_calendar_events_unique_external_index"
           )

    create unique_index(
             :canonical_calendar_events,
             [:organization_id, :external_system, :external_uid],
             name: "canonical_calendar_events_unique_provider_uid_index"
           )
  end

  def down do
    drop constraint(:canonical_calendar_events, "canonical_calendar_events_organizer_id_fkey")

    drop_if_exists unique_index(
                     :canonical_calendar_events,
                     [:organization_id, :external_system, :external_uid],
                     name: "canonical_calendar_events_unique_provider_uid_index"
                   )

    drop_if_exists unique_index(
                     :canonical_calendar_events,
                     [:organization_id, :external_system, :external_id],
                     name: "canonical_calendar_events_unique_external_index"
                   )

    drop table(:canonical_calendar_events)

    drop_if_exists unique_index(
                     :canonical_tasks,
                     [:organization_id, :external_system, :external_id],
                     name: "canonical_tasks_unique_external_index"
                   )

    drop table(:canonical_tasks)

    drop constraint(:canonical_messages, "canonical_messages_sender_id_fkey")

    drop constraint(:canonical_messages, "canonical_messages_conversation_id_fkey")

    alter table(:canonical_messages) do
      remove :sender_id
    end

    drop_if_exists unique_index(
                     :canonical_messages,
                     [:organization_id, :external_system, :external_id],
                     name: "canonical_messages_unique_external_index"
                   )

    drop table(:canonical_messages)

    drop_if_exists unique_index(
                     :canonical_projects,
                     [:organization_id, :external_system, :external_id],
                     name: "canonical_projects_unique_external_index"
                   )

    drop table(:canonical_projects)

    drop_if_exists unique_index(
                     :canonical_conversations,
                     [:organization_id, :external_system, :external_id],
                     name: "canonical_conversations_unique_external_index"
                   )

    drop table(:canonical_conversations)

    drop_if_exists unique_index(:canonical_people, [:organization_id, :email],
                     name: "canonical_people_unique_email_index"
                   )

    drop table(:canonical_people)

    drop_if_exists unique_index(:canonical_accounts, [:organization_id, :provider, :external_id],
                     name: "canonical_accounts_unique_provider_account_index"
                   )

    drop table(:canonical_accounts)
  end
end
