defmodule AshEnterprise.Repo.Migrations.AddContractsDomain do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("CREATE SCHEMA IF NOT EXISTS canonical")

    create table(:amendments, primary_key: false, prefix: "canonical") do
      add :lifecycle_status, :text, null: false, default: "active"
      add :version_number, :bigint, null: false, default: 1
      add :import_sequence_number, :bigint
      add :overridden_created_on, :utc_datetime_usec
      add :modified_on_behalf_by_id, :uuid
      add :created_on_behalf_by_id, :uuid
      add :modified_by_id, :uuid
      add :created_by_id, :uuid

      add :modified_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :created_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :contract_id, :uuid, null: false
      add :amendment_number, :bigint, null: false
      add :rationale, :text
      add :description, :text
      add :amended_at, :utc_datetime_usec
    end

    execute("CREATE SCHEMA IF NOT EXISTS canonical")

    create table(:milestones, primary_key: false, prefix: "canonical") do
      add :version_number, :bigint, null: false, default: 1
      add :import_sequence_number, :bigint
      add :overridden_created_on, :utc_datetime_usec
      add :modified_on_behalf_by_id, :uuid
      add :created_on_behalf_by_id, :uuid
      add :modified_by_id, :uuid
      add :created_by_id, :uuid

      add :modified_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :created_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :contract_id, :uuid, null: false
      add :commitment_id, :uuid
      add :milestone_code, :text, null: false
      add :title, :text, null: false
      add :due_date, :date
      add :notice_lead_days, :bigint
      add :completed_at, :utc_datetime_usec
    end

    execute("CREATE SCHEMA IF NOT EXISTS canonical")

    create table(:transactions, primary_key: false, prefix: "canonical") do
      add :version_number, :bigint, null: false, default: 1
      add :import_sequence_number, :bigint
      add :overridden_created_on, :utc_datetime_usec
      add :modified_on_behalf_by_id, :uuid
      add :created_on_behalf_by_id, :uuid
      add :modified_by_id, :uuid
      add :created_by_id, :uuid

      add :modified_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :created_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :contract_id, :uuid, null: false
      add :line_id, :uuid
      add :amount, :decimal, null: false
      add :currency, :text, null: false
      add :value_date, :date
      add :source, :text, null: false
      add :external_reference, :text, null: false
    end

    create unique_index(:transactions, [:source, :external_reference],
             name: "transactions_source_reference_index",
             prefix: "canonical"
           )
  end

  def down do
    drop_if_exists unique_index(:transactions, [:source, :external_reference],
                     name: "transactions_source_reference_index",
                     prefix: "canonical"
                   )

    drop table(:transactions, prefix: "canonical")

    drop table(:milestones, prefix: "canonical")

    drop table(:amendments, prefix: "canonical")
  end
end
