defmodule AshEnterprise.Repo.Migrations.AddJudgmentLedgerHosts do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:system_one_human_verdicts, primary_key: false) do
      add :organization_id, :uuid, null: false
      add :version_number, :bigint, null: false, default: 1
      add :import_sequence_number, :bigint
      add :overridden_created_on, :utc_datetime_usec
      add :modified_on_behalf_by_id, :uuid
      add :created_on_behalf_by_id, :uuid
      add :modified_by_id, :uuid
      add :created_by_id, :uuid

      add :modified_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :created_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :recorded_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :judgment_id, :uuid, null: false
      add :question_hash, :text, null: false
      add :question_version, :bigint
      add :model_digest, :text
      add :state_ref, :map
      add :model_answer, :map, null: false
      add :model_version, :text
      add :human_value, :text, null: false
      add :reason, :text
      add :reviewer, :text, null: false
      add :blind?, :boolean, default: false
      add :basis, :text, null: false, default: "override"
    end

    create table(:system_one_judgments, primary_key: false) do
      add :organization_id, :uuid, null: false
      add :version_number, :bigint, null: false, default: 1
      add :import_sequence_number, :bigint
      add :overridden_created_on, :utc_datetime_usec
      add :modified_on_behalf_by_id, :uuid
      add :created_on_behalf_by_id, :uuid
      add :modified_by_id, :uuid
      add :created_by_id, :uuid

      add :modified_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :created_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :recorded_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :record_version, :text, default: "0"
      add :record_hash, :text
      add :question_id, :text, null: false
      add :question_hash, :text, null: false
      add :question_version, :bigint, null: false
      add :family, :text, null: false
      add :subject_type, :text
      add :subject_id, :text
      add :rule_id, :text
      add :predicate_id, :text
      add :atom_ids, {:array, :text}
      add :document_hash, :text
      add :parser_version, :text
      add :state_digest, :text, null: false
      add :state_ref, :map
      add :state_ciphertext, :binary
      add :answer_kind, :text, null: false
      add :value, :text
      add :probabilities, :map
      add :confidence, :decimal
      add :model_spec_requested, :text, null: false
      add :model_version, :text
      add :model_digest, :text
      add :runtime_version, :text
      add :profile, :text, null: false
      add :residency, :text, default: "in_cluster"
      add :usage, :map
      add :latency_us, :bigint
      add :cache_key, :text, null: false
      add :mode, :text, null: false, default: "live"
      add :region, :text, null: false
      add :correlation_id, :uuid
      add :envelope, :map
      add :valid_until, :utc_datetime_usec
    end

    create unique_index(:system_one_judgments, [:organization_id, :id],
             name: "system_one_judgments_unique_id_index"
           )
  end

  def down do
    drop_if_exists unique_index(:system_one_judgments, [:organization_id, :id],
                     name: "system_one_judgments_unique_id_index"
                   )

    drop table(:system_one_judgments)

    drop table(:system_one_human_verdicts)
  end
end
