defmodule AshEnterprise.Repo.Migrations.NlFilterProposals do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:system_one_filter_executions, primary_key: false) do
      add :organization_id, :uuid, null: false
      add :version_number, :bigint, null: false, default: 1
      add :import_sequence_number, :bigint
      add :overridden_created_on, :utc_datetime_usec
      add :modified_on_behalf_by_id, :uuid
      add :created_on_behalf_by_id, :uuid
      add :modified_by_id, :uuid
      add :created_by_id, :uuid

      add :modified_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :created_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :proposal_id, :uuid, null: false
      add :proposal_version, :bigint, null: false
      add :document, :map, null: false
      add :plan, :map, null: false
      add :in_count, :bigint, null: false, default: 0
      add :out_count, :bigint, null: false, default: 0
      add :unknown_count, :bigint, null: false, default: 0
      add :min_grade, :text, null: false
      add :scope, :map
      add :wire_question_hash, :text, null: false
      add :nl_digest, :text, null: false

      add :ran_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:system_one_filter_proposals, primary_key: false) do
      add :organization_id, :uuid, null: false
      add :version_number, :bigint, null: false, default: 1
      add :import_sequence_number, :bigint
      add :overridden_created_on, :utc_datetime_usec
      add :modified_on_behalf_by_id, :uuid
      add :created_on_behalf_by_id, :uuid
      add :modified_by_id, :uuid
      add :created_by_id, :uuid

      add :modified_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :created_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :status, :text, null: false, default: "proposed"
      add :source, :text, null: false, default: "search"
      add :nl_text, :text, null: false
      add :nl_digest, :text, null: false
      add :document, :map
      add :refusal_reason, :text
      add :raw_output, :text
      add :profile, :text, null: false
      add :question_id, :text, null: false
      add :wire_question_hash, :text, null: false
      add :queryables_hash, :text, null: false
      add :version, :bigint, null: false, default: 1
      add :root_id, :uuid
      add :supersedes_id, :uuid

      add :proposed_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop table(:system_one_filter_proposals)

    drop table(:system_one_filter_executions)
  end
end
