defmodule AshEnterprise.Repo.Migrations.AddSystemOneEvidenceAdjudication do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:system_one_evidence_assertions, primary_key: false) do
      add :organization_id, :uuid, null: false
      add :version_number, :bigint, null: false, default: 1
      add :import_sequence_number, :bigint
      add :overridden_created_on, :utc_datetime_usec
      add :modified_on_behalf_by_id, :uuid
      add :created_on_behalf_by_id, :uuid
      add :modified_by_id, :uuid
      add :created_by_id, :uuid

      add :modified_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :created_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :record_version, :text
      add :record_hash, :text
      add :packet_id, :uuid
      add :evaluation_id, :uuid
      add :disposition, :text, null: false
      add :distribution, :map, null: false
      add :aggregation_rule_version, :text, null: false
      add :observation_ids, {:array, :uuid}, null: false, default: []
      add :subject, :map, null: false
      add :predicate, :text, null: false
      add :subject_state_digest, :text, null: false
      add :question_set_hash, :text, null: false
    end

    create unique_index(:system_one_evidence_assertions, [:organization_id, :id],
             name: "system_one_evidence_assertions_unique_id_index"
           )
  end

  def down do
    drop_if_exists unique_index(:system_one_evidence_assertions, [:organization_id, :id],
                     name: "system_one_evidence_assertions_unique_id_index"
                   )

    drop table(:system_one_evidence_assertions)
  end
end
