defmodule AshEnterprise.Repo.Migrations.InstallBtreeGist do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:audit_events) do
      modify :id, :uuid, default: fragment("uuidv7()")
    end
  end

  def down do
    alter table(:audit_events) do
      modify :id, :uuid, default: fragment("uuid_generate_v7()")
    end
  end
end
