defmodule AshEnterprise.Repo.Migrations.AddAgentMorningBriefs do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:agent_morning_briefs, primary_key: false) do
      add :organization_id, :uuid, null: false
      add :owning_team_id, :uuid
      add :owning_user_id, :uuid
      add :owner_type, :text, null: false, default: "user"
      add :owner_id, :uuid, null: false
      add :owning_business_unit_id, :uuid
      add :version_number, :bigint, null: false, default: 1
      add :import_sequence_number, :bigint
      add :overridden_created_on, :utc_datetime_usec
      add :modified_on_behalf_by_id, :uuid
      add :created_on_behalf_by_id, :uuid
      add :modified_by_id, :uuid
      add :created_by_id, :uuid

      add :modified_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :created_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :brief_date, :date, null: false
      add :draft_text, :text
      add :status, :text, null: false, default: "pending_approval"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop table(:agent_morning_briefs)
  end
end
