defmodule AshEnterprise.Repo.Migrations.AddLifecycleStateMachine do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      remove :state_code
      remove :status_code
      add :lifecycle_status, :text, null: false, default: "active"
    end

    alter table(:teams) do
      remove :state_code
      remove :status_code
      add :lifecycle_status, :text, null: false, default: "active"
    end

    alter table(:roles) do
      remove :state_code
      remove :status_code
      add :lifecycle_status, :text, null: false, default: "active"
    end

    alter table(:positions) do
      remove :state_code
      remove :status_code
      add :lifecycle_status, :text, null: false, default: "active"
    end

    alter table(:organizations) do
      remove :state_code
      remove :status_code
      add :lifecycle_status, :text, null: false, default: "active"
    end

    alter table(:business_units) do
      remove :state_code
      remove :status_code
      add :lifecycle_status, :text, null: false, default: "active"
    end
  end

  def down do
    alter table(:business_units) do
      remove :lifecycle_status
      add :status_code, :bigint
      add :state_code, :bigint, null: false, default: 0
    end

    alter table(:organizations) do
      remove :lifecycle_status
      add :status_code, :bigint
      add :state_code, :bigint, null: false, default: 0
    end

    alter table(:positions) do
      remove :lifecycle_status
      add :status_code, :bigint
      add :state_code, :bigint, null: false, default: 0
    end

    alter table(:roles) do
      remove :lifecycle_status
      add :status_code, :bigint
      add :state_code, :bigint, null: false, default: 0
    end

    alter table(:teams) do
      remove :lifecycle_status
      add :status_code, :bigint
      add :state_code, :bigint, null: false, default: 0
    end

    alter table(:users) do
      remove :lifecycle_status
      add :status_code, :bigint
      add :state_code, :bigint, null: false, default: 0
    end
  end
end
