defmodule AshEnterprise.Repo.Migrations.BpmnWaitingTokensAndChildInstances do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:bpmn_tokens) do
      add :parked_at, :utc_datetime_usec
      add :correlation_key, :text
      add :subscription_signature, :text
      add :lookback_until, :utc_datetime_usec
    end

    create index(:bpmn_tokens, [:organization_id, :subscription_signature, :instance_id],
             name: "bpmn_tokens_waiting_index",
             where: "status = 'waiting'"
           )

    alter table(:bpmn_instances) do
      add :parent_instance_id, :uuid
      add :parent_token_id, :uuid
      add :trigger_depth, :bigint, null: false, default: 0
    end
  end

  def down do
    alter table(:bpmn_instances) do
      remove :trigger_depth
      remove :parent_token_id
      remove :parent_instance_id
    end

    drop_if_exists index(:bpmn_tokens, [:organization_id, :subscription_signature, :instance_id],
                     name: "bpmn_tokens_waiting_index"
                   )

    alter table(:bpmn_tokens) do
      remove :lookback_until
      remove :subscription_signature
      remove :correlation_key
      remove :parked_at
    end
  end
end
