defmodule AshEnterprise.Repo.Migrations.FixBusinessUnitPathIndex do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists index(:business_units, [:organization_id, "organization_id", "path"],
                     name: "business_units_org_path_prefix_index"
                   )

    create index(:business_units, [:organization_id, "organization_id", "path text_pattern_ops"],
             name: "business_units_org_path_prefix_index",
             using: "btree"
           )
  end

  def down do
    drop_if_exists index(
                     :business_units,
                     [:organization_id, "organization_id", "path text_pattern_ops"],
                     name: "business_units_org_path_prefix_index"
                   )

    create index(:business_units, [:organization_id, "organization_id", "path"],
             name: "business_units_org_path_prefix_index",
             using: "btree"
           )
  end
end
