defmodule AshEnterprise.Repo.Migrations.AddProjectorEngineTables do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:ash_projection_registry, primary_key: false) do
      add :name, :text, null: false, primary_key: true
      add :status, :text, null: false, default: "active"
      add :version, :bigint, null: false, default: 1

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:ash_projection_registry, [:name],
             name: "ash_projection_registry_by_name_index"
           )

    create table(:ash_projection_dead_letter_events, primary_key: false) do
      add :projection_name, :text, null: false, primary_key: true
      add :event_id, :bigint, null: false, primary_key: true
      add :status, :text, null: false, default: "failed"
      add :error_class, :text, null: false
      add :error_message, :text, null: false
      add :stacktrace, :text
      add :failed_at, :utc_datetime_usec, null: false
      add :replayed_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:ash_projection_dead_letter_events, [:projection_name, :event_id],
             name: "ash_projection_dead_letter_events_by_projection_and_event_index"
           )

    create table(:ash_projection_checkpoints, primary_key: false) do
      add :projection_name, :text, null: false, primary_key: true
      add :last_seen_event_id, :bigint
      add :events_processed, :bigint, null: false, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:ash_projection_checkpoints, [:projection_name],
             name: "ash_projection_checkpoints_by_name_index"
           )
  end

  def down do
    drop_if_exists unique_index(:ash_projection_checkpoints, [:projection_name],
                     name: "ash_projection_checkpoints_by_name_index"
                   )

    drop table(:ash_projection_checkpoints)

    drop_if_exists unique_index(:ash_projection_dead_letter_events, [:projection_name, :event_id],
                     name: "ash_projection_dead_letter_events_by_projection_and_event_index"
                   )

    drop table(:ash_projection_dead_letter_events)

    drop_if_exists unique_index(:ash_projection_registry, [:name],
                     name: "ash_projection_registry_by_name_index"
                   )

    drop table(:ash_projection_registry)
  end
end
