defmodule AshEnterprise.Repo.Migrations.AddStranglerCompatibility do
  @moduledoc """
  Strangler compatibility layer, generated by `mix ash_strangler.gen.migration`.

  Covers: AshEnterprise.Legacy.User, AshEnterprise.Contracts.Party, AshEnterprise.Contracts.PartyFromVendor, AshEnterprise.Contracts.PartyFromEnterprise, AshEnterprise.Contracts.ContractingProcess, AshEnterprise.Contracts.PartyRole, AshEnterprise.Contracts.Contract, AshEnterprise.Contracts.ContractLine, AshEnterprise.Contracts.Commitment

  Regenerate rather than hand-editing. Every statement is idempotent
  (`CREATE OR REPLACE`, `IF NOT EXISTS`), so re-running this after a mapping
  change is safe.
  """

  use Ecto.Migration

  def up do
    execute("""
    CREATE SCHEMA IF NOT EXISTS "strangler";
    """)

    execute("""
    CREATE OR REPLACE VIEW "strangler"."users" AS
    SELECT
      uuid_generate_v5('ce41843a-c056-4c3e-9c79-50e7e5f4887c'::uuid, 'legacy.users:' || id::text) AS id,
      id AS __legacy_id,
      ('00000000-0000-0000-0000-0000000000fe')::uuid AS organization_id,
      ('00000000-0000-0000-0000-0000000000fd')::uuid AS owning_business_unit_id,
      (CASE WHEN (state = 'active') THEN ('active')::text ELSE ('inactive')::text END) AS lifecycle_status,
      1 AS version_number,
      NULL AS import_sequence_number,
      NULL AS overridden_created_on,
      NULL AS modified_on_behalf_by_id,
      NULL AS created_on_behalf_by_id,
      NULL AS modified_by_id,
      NULL AS created_by_id,
      (updated_at AT TIME ZONE 'UTC') AS modified_on,
      (created_at AT TIME ZONE 'UTC') AS created_on,
      id AS legacy_id,
      login AS login,
      (email)::citext AS email,
      (coalesce(first_name, '') || (' ' || coalesce(last_name, ''))) AS full_name,
      (state)::text AS legacy_state,
      (deleted_at AT TIME ZONE 'UTC') AS archived_at
    FROM legacy.users;
    """)

    execute("""
    CREATE INDEX IF NOT EXISTS strangler_users_key_idx ON legacy.users
      (uuid_generate_v5('ce41843a-c056-4c3e-9c79-50e7e5f4887c'::uuid, 'legacy.users:' || id::text));
    """)

    execute("""
    CREATE OR REPLACE FUNCTION "strangler"."strangler_users_notify"() RETURNS trigger AS $strangler$
    DECLARE
      affected record;
    BEGIN
      affected := COALESCE(NEW, OLD);

      -- Key only. See the moduledoc: a payload built from row data can exceed
      -- the 7999-byte ceiling and abort the LEGACY application's transaction.
      PERFORM pg_notify('ash_strangler', json_build_object(
        'resource', 'Elixir.AshEnterprise.Legacy.User',
        'legacy_id', affected.id,
        'op', lower(TG_OP)
      )::text);

      -- The return value of an AFTER row trigger is ignored.
      RETURN NULL;
    END $strangler$ LANGUAGE plpgsql;
    """)

    execute("""
    CREATE OR REPLACE TRIGGER "strangler_users_notify"
      AFTER INSERT OR UPDATE OR DELETE ON legacy.users
      FOR EACH ROW EXECUTE FUNCTION "strangler"."strangler_users_notify"();
    """)

    execute("""
    CREATE OR REPLACE VIEW "strangler"."parties" AS
    SELECT
      id::uuid AS id,
      id AS __legacy_id,
      NULL AS version_number,
      NULL AS import_sequence_number,
      NULL AS overridden_created_on,
      NULL AS modified_on_behalf_by_id,
      NULL AS created_on_behalf_by_id,
      NULL AS modified_by_id,
      NULL AS created_by_id,
      NULL AS modified_on,
      (created_at AT TIME ZONE 'UTC') AS created_on,
      name AS legal_name,
      client_id AS client_id,
      metadata AS metadata
    FROM public.clm_parties;
    """)

    execute("""
    CREATE OR REPLACE FUNCTION "strangler"."strangler_parties_notify"() RETURNS trigger AS $strangler$
    DECLARE
      affected record;
    BEGIN
      affected := COALESCE(NEW, OLD);

      -- Key only. See the moduledoc: a payload built from row data can exceed
      -- the 7999-byte ceiling and abort the LEGACY application's transaction.
      PERFORM pg_notify('ash_strangler', json_build_object(
        'resource', 'Elixir.AshEnterprise.Contracts.Party',
        'legacy_id', affected.id,
        'op', lower(TG_OP)
      )::text);

      -- The return value of an AFTER row trigger is ignored.
      RETURN NULL;
    END $strangler$ LANGUAGE plpgsql;
    """)

    execute("""
    CREATE OR REPLACE TRIGGER "strangler_parties_notify"
      AFTER INSERT OR UPDATE OR DELETE ON public.clm_parties
      FOR EACH ROW EXECUTE FUNCTION "strangler"."strangler_parties_notify"();
    """)

    execute("""
    CREATE OR REPLACE VIEW "strangler"."vendor_parties" AS
    SELECT
      uuid_generate_v5('ce41843a-c056-4c3e-9c79-50e7e5f4887c'::uuid, 'vendorpm.vendors:' || id::text) AS id,
      id AS __legacy_id,
      NULL AS version_number,
      NULL AS import_sequence_number,
      NULL AS overridden_created_on,
      NULL AS modified_on_behalf_by_id,
      NULL AS created_on_behalf_by_id,
      NULL AS modified_by_id,
      NULL AS created_by_id,
      NULL AS modified_on,
      created AS created_on,
      company AS legal_name,
      email AS email,
      phone AS phone,
      verified_status AS verified_status,
      blacklisted AS blacklisted,
      onboarding AS onboarding
    FROM vendorpm.vendors;
    """)

    execute("""
    CREATE INDEX IF NOT EXISTS strangler_vendor_parties_key_idx ON vendorpm.vendors
      (uuid_generate_v5('ce41843a-c056-4c3e-9c79-50e7e5f4887c'::uuid, 'vendorpm.vendors:' || id::text));
    """)

    execute("""
    CREATE OR REPLACE FUNCTION "strangler"."strangler_vendor_parties_notify"() RETURNS trigger AS $strangler$
    DECLARE
      affected record;
    BEGIN
      affected := COALESCE(NEW, OLD);

      -- Key only. See the moduledoc: a payload built from row data can exceed
      -- the 7999-byte ceiling and abort the LEGACY application's transaction.
      PERFORM pg_notify('ash_strangler', json_build_object(
        'resource', 'Elixir.AshEnterprise.Contracts.PartyFromVendor',
        'legacy_id', affected.id,
        'op', lower(TG_OP)
      )::text);

      -- The return value of an AFTER row trigger is ignored.
      RETURN NULL;
    END $strangler$ LANGUAGE plpgsql;
    """)

    execute("""
    CREATE OR REPLACE TRIGGER "strangler_vendor_parties_notify"
      AFTER INSERT OR UPDATE OR DELETE ON vendorpm.vendors
      FOR EACH ROW EXECUTE FUNCTION "strangler"."strangler_vendor_parties_notify"();
    """)

    execute("""
    CREATE OR REPLACE VIEW "strangler"."enterprise_parties" AS
    SELECT
      uuid_generate_v5('ce41843a-c056-4c3e-9c79-50e7e5f4887c'::uuid, 'vendorpm.enterprises:' || id::text) AS id,
      id AS __legacy_id,
      NULL AS version_number,
      NULL AS import_sequence_number,
      NULL AS overridden_created_on,
      NULL AS modified_on_behalf_by_id,
      NULL AS created_on_behalf_by_id,
      NULL AS modified_by_id,
      NULL AS created_by_id,
      NULL AS modified_on,
      created AS created_on,
      company AS legal_name,
      data_region AS data_region
    FROM vendorpm.enterprises;
    """)

    execute("""
    CREATE INDEX IF NOT EXISTS strangler_enterprise_parties_key_idx ON vendorpm.enterprises
      (uuid_generate_v5('ce41843a-c056-4c3e-9c79-50e7e5f4887c'::uuid, 'vendorpm.enterprises:' || id::text));
    """)

    execute("""
    CREATE OR REPLACE FUNCTION "strangler"."strangler_enterprise_parties_notify"() RETURNS trigger AS $strangler$
    DECLARE
      affected record;
    BEGIN
      affected := COALESCE(NEW, OLD);

      -- Key only. See the moduledoc: a payload built from row data can exceed
      -- the 7999-byte ceiling and abort the LEGACY application's transaction.
      PERFORM pg_notify('ash_strangler', json_build_object(
        'resource', 'Elixir.AshEnterprise.Contracts.PartyFromEnterprise',
        'legacy_id', affected.id,
        'op', lower(TG_OP)
      )::text);

      -- The return value of an AFTER row trigger is ignored.
      RETURN NULL;
    END $strangler$ LANGUAGE plpgsql;
    """)

    execute("""
    CREATE OR REPLACE TRIGGER "strangler_enterprise_parties_notify"
      AFTER INSERT OR UPDATE OR DELETE ON vendorpm.enterprises
      FOR EACH ROW EXECUTE FUNCTION "strangler"."strangler_enterprise_parties_notify"();
    """)

    execute("""
    CREATE OR REPLACE VIEW "strangler"."contracting_processes" AS
    SELECT
      uuid_generate_v5('ce41843a-c056-4c3e-9c79-50e7e5f4887c'::uuid, 'vendorpm.rfqs:' || id::text) AS id,
      id AS __legacy_id,
      NULL AS version_number,
      NULL AS import_sequence_number,
      NULL AS overridden_created_on,
      NULL AS modified_on_behalf_by_id,
      NULL AS created_on_behalf_by_id,
      NULL AS modified_by_id,
      NULL AS created_by_id,
      last_modified AS modified_on,
      created AS created_on,
      ('ocds-vpm-' || (id)::text) AS ocid,
      additional_message AS title,
      deadline AS deadline,
      cancel_reason AS cancel_reason,
      (CASE WHEN (cancelled IS NOT NULL) THEN 'cancelled' ELSE (CASE WHEN (submitted IS NOT NULL) THEN 'published' ELSE 'draft' END) END) AS lifecycle_status
    FROM vendorpm.rfqs;
    """)

    execute("""
    CREATE INDEX IF NOT EXISTS strangler_contracting_processes_key_idx ON vendorpm.rfqs
      (uuid_generate_v5('ce41843a-c056-4c3e-9c79-50e7e5f4887c'::uuid, 'vendorpm.rfqs:' || id::text));
    """)

    execute("""
    CREATE OR REPLACE FUNCTION "strangler"."strangler_contracting_processes_notify"() RETURNS trigger AS $strangler$
    DECLARE
      affected record;
    BEGIN
      affected := COALESCE(NEW, OLD);

      -- Key only. See the moduledoc: a payload built from row data can exceed
      -- the 7999-byte ceiling and abort the LEGACY application's transaction.
      PERFORM pg_notify('ash_strangler', json_build_object(
        'resource', 'Elixir.AshEnterprise.Contracts.ContractingProcess',
        'legacy_id', affected.id,
        'op', lower(TG_OP)
      )::text);

      -- The return value of an AFTER row trigger is ignored.
      RETURN NULL;
    END $strangler$ LANGUAGE plpgsql;
    """)

    execute("""
    CREATE OR REPLACE TRIGGER "strangler_contracting_processes_notify"
      AFTER INSERT OR UPDATE OR DELETE ON vendorpm.rfqs
      FOR EACH ROW EXECUTE FUNCTION "strangler"."strangler_contracting_processes_notify"();
    """)

    execute("""
    CREATE OR REPLACE VIEW "strangler"."party_roles" AS
    SELECT
      uuid_generate_v5('ce41843a-c056-4c3e-9c79-50e7e5f4887c'::uuid, 'vendorpm.rfq_responses:' || id::text) AS id,
      id AS __legacy_id,
      NULL AS version_number,
      NULL AS import_sequence_number,
      NULL AS overridden_created_on,
      NULL AS modified_on_behalf_by_id,
      NULL AS created_on_behalf_by_id,
      NULL AS modified_by_id,
      NULL AS created_by_id,
      NULL AS modified_on,
      created AS created_on,
      rfq_id AS legacy_rfq_id,
      vendor_id AS legacy_party_id,
      ('supplier')::text AS role,
      interested AS interested,
      reason AS reason,
      additional_insured_document AS additional_insured_document
    FROM vendorpm.rfq_responses;
    """)

    execute("""
    CREATE INDEX IF NOT EXISTS strangler_party_roles_key_idx ON vendorpm.rfq_responses
      (uuid_generate_v5('ce41843a-c056-4c3e-9c79-50e7e5f4887c'::uuid, 'vendorpm.rfq_responses:' || id::text));
    """)

    execute("""
    CREATE OR REPLACE FUNCTION "strangler"."strangler_party_roles_notify"() RETURNS trigger AS $strangler$
    DECLARE
      affected record;
    BEGIN
      affected := COALESCE(NEW, OLD);

      -- Key only. See the moduledoc: a payload built from row data can exceed
      -- the 7999-byte ceiling and abort the LEGACY application's transaction.
      PERFORM pg_notify('ash_strangler', json_build_object(
        'resource', 'Elixir.AshEnterprise.Contracts.PartyRole',
        'legacy_id', affected.id,
        'op', lower(TG_OP)
      )::text);

      -- The return value of an AFTER row trigger is ignored.
      RETURN NULL;
    END $strangler$ LANGUAGE plpgsql;
    """)

    execute("""
    CREATE OR REPLACE TRIGGER "strangler_party_roles_notify"
      AFTER INSERT OR UPDATE OR DELETE ON vendorpm.rfq_responses
      FOR EACH ROW EXECUTE FUNCTION "strangler"."strangler_party_roles_notify"();
    """)

    execute("""
    CREATE OR REPLACE VIEW "strangler"."contracts" AS
    SELECT
      id::uuid AS id,
      id AS __legacy_id,
      NULL AS version_number,
      NULL AS import_sequence_number,
      NULL AS overridden_created_on,
      NULL AS modified_on_behalf_by_id,
      NULL AS created_on_behalf_by_id,
      NULL AS modified_by_id,
      NULL AS created_by_id,
      NULL AS modified_on,
      (createdAt AT TIME ZONE 'UTC') AS created_on,
      name AS name,
      description AS description,
      effectiveDate AS effective_date,
      expiryDate AS expiry_date,
      value AS value,
      paymentTerm AS payment_term,
      clauses AS clauses,
      metadata AS metadata,
      serviceProviderPartyId AS service_provider_party_id,
      clientPartyId AS client_party_id,
      (CASE WHEN (archived IS NOT NULL) THEN 'archived' ELSE (CASE WHEN (processed AND (NOT verified)) THEN 'unverified' ELSE (CASE WHEN (processed AND verified) THEN 'active' ELSE 'processing' END) END) END) AS lifecycle_status
    FROM public.clm_contracts;
    """)

    execute("""
    CREATE OR REPLACE FUNCTION "strangler"."strangler_contracts_notify"() RETURNS trigger AS $strangler$
    DECLARE
      affected record;
    BEGIN
      affected := COALESCE(NEW, OLD);

      -- Key only. See the moduledoc: a payload built from row data can exceed
      -- the 7999-byte ceiling and abort the LEGACY application's transaction.
      PERFORM pg_notify('ash_strangler', json_build_object(
        'resource', 'Elixir.AshEnterprise.Contracts.Contract',
        'legacy_id', affected.id,
        'op', lower(TG_OP)
      )::text);

      -- The return value of an AFTER row trigger is ignored.
      RETURN NULL;
    END $strangler$ LANGUAGE plpgsql;
    """)

    execute("""
    CREATE OR REPLACE TRIGGER "strangler_contracts_notify"
      AFTER INSERT OR UPDATE OR DELETE ON public.clm_contracts
      FOR EACH ROW EXECUTE FUNCTION "strangler"."strangler_contracts_notify"();
    """)

    execute("""
    CREATE OR REPLACE VIEW "strangler"."contract_lines" AS
    SELECT
      uuid_generate_v5('ce41843a-c056-4c3e-9c79-50e7e5f4887c'::uuid, 'vendorpm.quotes:' || id::text) AS id,
      id AS __legacy_id,
      NULL AS version_number,
      NULL AS import_sequence_number,
      NULL AS overridden_created_on,
      NULL AS modified_on_behalf_by_id,
      NULL AS created_on_behalf_by_id,
      NULL AS modified_by_id,
      NULL AS created_by_id,
      updated AS modified_on,
      created AS created_on,
      rfq_id AS legacy_rfq_id,
      vendor_id AS legacy_party_id,
      total_price AS total_price,
      submitted AS submitted,
      procurement_review_complete AS procurement_review_complete
    FROM vendorpm.quotes;
    """)

    execute("""
    CREATE INDEX IF NOT EXISTS strangler_contract_lines_key_idx ON vendorpm.quotes
      (uuid_generate_v5('ce41843a-c056-4c3e-9c79-50e7e5f4887c'::uuid, 'vendorpm.quotes:' || id::text));
    """)

    execute("""
    CREATE OR REPLACE FUNCTION "strangler"."strangler_contract_lines_notify"() RETURNS trigger AS $strangler$
    DECLARE
      affected record;
    BEGIN
      affected := COALESCE(NEW, OLD);

      -- Key only. See the moduledoc: a payload built from row data can exceed
      -- the 7999-byte ceiling and abort the LEGACY application's transaction.
      PERFORM pg_notify('ash_strangler', json_build_object(
        'resource', 'Elixir.AshEnterprise.Contracts.ContractLine',
        'legacy_id', affected.id,
        'op', lower(TG_OP)
      )::text);

      -- The return value of an AFTER row trigger is ignored.
      RETURN NULL;
    END $strangler$ LANGUAGE plpgsql;
    """)

    execute("""
    CREATE OR REPLACE TRIGGER "strangler_contract_lines_notify"
      AFTER INSERT OR UPDATE OR DELETE ON vendorpm.quotes
      FOR EACH ROW EXECUTE FUNCTION "strangler"."strangler_contract_lines_notify"();
    """)

    execute("""
    CREATE OR REPLACE VIEW "strangler"."commitments" AS
    SELECT
      uuid_generate_v5('ce41843a-c056-4c3e-9c79-50e7e5f4887c'::uuid, 'vendorpm.compliance_documents:' || id::text) AS id,
      id AS __legacy_id,
      NULL AS version_number,
      NULL AS import_sequence_number,
      NULL AS overridden_created_on,
      NULL AS modified_on_behalf_by_id,
      NULL AS created_on_behalf_by_id,
      NULL AS modified_by_id,
      NULL AS created_by_id,
      NULL AS modified_on,
      created AS created_on,
      vendor_id AS legacy_party_id,
      ('compliance')::text AS commitment_type,
      status AS status,
      expiry_date AS effective_date,
      attachment AS attachment
    FROM vendorpm.compliance_documents;
    """)

    execute("""
    CREATE INDEX IF NOT EXISTS strangler_commitments_key_idx ON vendorpm.compliance_documents
      (uuid_generate_v5('ce41843a-c056-4c3e-9c79-50e7e5f4887c'::uuid, 'vendorpm.compliance_documents:' || id::text));
    """)

    execute("""
    CREATE OR REPLACE FUNCTION "strangler"."strangler_commitments_notify"() RETURNS trigger AS $strangler$
    DECLARE
      affected record;
    BEGIN
      affected := COALESCE(NEW, OLD);

      -- Key only. See the moduledoc: a payload built from row data can exceed
      -- the 7999-byte ceiling and abort the LEGACY application's transaction.
      PERFORM pg_notify('ash_strangler', json_build_object(
        'resource', 'Elixir.AshEnterprise.Contracts.Commitment',
        'legacy_id', affected.id,
        'op', lower(TG_OP)
      )::text);

      -- The return value of an AFTER row trigger is ignored.
      RETURN NULL;
    END $strangler$ LANGUAGE plpgsql;
    """)

    execute("""
    CREATE OR REPLACE TRIGGER "strangler_commitments_notify"
      AFTER INSERT OR UPDATE OR DELETE ON vendorpm.compliance_documents
      FOR EACH ROW EXECUTE FUNCTION "strangler"."strangler_commitments_notify"();
    """)
  end

  def down do
    execute("""
    DO $strangler$
    BEGIN
      IF to_regclass('vendorpm.compliance_documents') IS NOT NULL THEN
        EXECUTE 'DROP TRIGGER IF EXISTS "strangler_commitments_notify" ON vendorpm.compliance_documents';
      END IF;
    END $strangler$;
    """)

    execute("""
    DROP FUNCTION IF EXISTS "strangler"."strangler_commitments_notify"() CASCADE;
    """)

    execute("""
    DROP INDEX IF EXISTS vendorpm.strangler_commitments_key_idx;
    """)

    execute("""
    DROP VIEW IF EXISTS "strangler"."commitments";
    """)

    execute("""
    DO $strangler$
    BEGIN
      IF to_regclass('vendorpm.quotes') IS NOT NULL THEN
        EXECUTE 'DROP TRIGGER IF EXISTS "strangler_contract_lines_notify" ON vendorpm.quotes';
      END IF;
    END $strangler$;
    """)

    execute("""
    DROP FUNCTION IF EXISTS "strangler"."strangler_contract_lines_notify"() CASCADE;
    """)

    execute("""
    DROP INDEX IF EXISTS vendorpm.strangler_contract_lines_key_idx;
    """)

    execute("""
    DROP VIEW IF EXISTS "strangler"."contract_lines";
    """)

    execute("""
    DO $strangler$
    BEGIN
      IF to_regclass('public.clm_contracts') IS NOT NULL THEN
        EXECUTE 'DROP TRIGGER IF EXISTS "strangler_contracts_notify" ON public.clm_contracts';
      END IF;
    END $strangler$;
    """)

    execute("""
    DROP FUNCTION IF EXISTS "strangler"."strangler_contracts_notify"() CASCADE;
    """)

    execute("""
    DROP VIEW IF EXISTS "strangler"."contracts";
    """)

    execute("""
    DO $strangler$
    BEGIN
      IF to_regclass('vendorpm.rfq_responses') IS NOT NULL THEN
        EXECUTE 'DROP TRIGGER IF EXISTS "strangler_party_roles_notify" ON vendorpm.rfq_responses';
      END IF;
    END $strangler$;
    """)

    execute("""
    DROP FUNCTION IF EXISTS "strangler"."strangler_party_roles_notify"() CASCADE;
    """)

    execute("""
    DROP INDEX IF EXISTS vendorpm.strangler_party_roles_key_idx;
    """)

    execute("""
    DROP VIEW IF EXISTS "strangler"."party_roles";
    """)

    execute("""
    DO $strangler$
    BEGIN
      IF to_regclass('vendorpm.rfqs') IS NOT NULL THEN
        EXECUTE 'DROP TRIGGER IF EXISTS "strangler_contracting_processes_notify" ON vendorpm.rfqs';
      END IF;
    END $strangler$;
    """)

    execute("""
    DROP FUNCTION IF EXISTS "strangler"."strangler_contracting_processes_notify"() CASCADE;
    """)

    execute("""
    DROP INDEX IF EXISTS vendorpm.strangler_contracting_processes_key_idx;
    """)

    execute("""
    DROP VIEW IF EXISTS "strangler"."contracting_processes";
    """)

    execute("""
    DO $strangler$
    BEGIN
      IF to_regclass('vendorpm.enterprises') IS NOT NULL THEN
        EXECUTE 'DROP TRIGGER IF EXISTS "strangler_enterprise_parties_notify" ON vendorpm.enterprises';
      END IF;
    END $strangler$;
    """)

    execute("""
    DROP FUNCTION IF EXISTS "strangler"."strangler_enterprise_parties_notify"() CASCADE;
    """)

    execute("""
    DROP INDEX IF EXISTS vendorpm.strangler_enterprise_parties_key_idx;
    """)

    execute("""
    DROP VIEW IF EXISTS "strangler"."enterprise_parties";
    """)

    execute("""
    DO $strangler$
    BEGIN
      IF to_regclass('vendorpm.vendors') IS NOT NULL THEN
        EXECUTE 'DROP TRIGGER IF EXISTS "strangler_vendor_parties_notify" ON vendorpm.vendors';
      END IF;
    END $strangler$;
    """)

    execute("""
    DROP FUNCTION IF EXISTS "strangler"."strangler_vendor_parties_notify"() CASCADE;
    """)

    execute("""
    DROP INDEX IF EXISTS vendorpm.strangler_vendor_parties_key_idx;
    """)

    execute("""
    DROP VIEW IF EXISTS "strangler"."vendor_parties";
    """)

    execute("""
    DO $strangler$
    BEGIN
      IF to_regclass('public.clm_parties') IS NOT NULL THEN
        EXECUTE 'DROP TRIGGER IF EXISTS "strangler_parties_notify" ON public.clm_parties';
      END IF;
    END $strangler$;
    """)

    execute("""
    DROP FUNCTION IF EXISTS "strangler"."strangler_parties_notify"() CASCADE;
    """)

    execute("""
    DROP VIEW IF EXISTS "strangler"."parties";
    """)

    execute("""
    DO $strangler$
    BEGIN
      IF to_regclass('legacy.users') IS NOT NULL THEN
        EXECUTE 'DROP TRIGGER IF EXISTS "strangler_users_notify" ON legacy.users';
      END IF;
    END $strangler$;
    """)

    execute("""
    DROP FUNCTION IF EXISTS "strangler"."strangler_users_notify"() CASCADE;
    """)

    execute("""
    DROP INDEX IF EXISTS legacy.strangler_users_key_idx;
    """)

    execute("""
    DROP VIEW IF EXISTS "strangler"."users";
    """)

    execute("""
    DO $strangler$
    BEGIN
      IF NOT EXISTS (
        SELECT 1
          FROM pg_class c
          JOIN pg_namespace n ON n.oid = c.relnamespace
         WHERE n.nspname = 'strangler'
      ) AND NOT EXISTS (
        SELECT 1
          FROM pg_proc p
          JOIN pg_namespace n ON n.oid = p.pronamespace
         WHERE n.nspname = 'strangler'
      ) THEN
        EXECUTE 'DROP SCHEMA IF EXISTS "strangler"';
      END IF;
    END $strangler$;
    """)
  end
end
