defmodule AshEnterprise.Repo.Migrations.AddIngestionDomain do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:ingestion_source_objects, primary_key: false) do
      add :version_number, :bigint, null: false, default: 1
      add :import_sequence_number, :bigint
      add :overridden_created_on, :utc_datetime_usec
      add :modified_on_behalf_by_id, :uuid
      add :created_on_behalf_by_id, :uuid
      add :modified_by_id, :uuid
      add :created_by_id, :uuid

      add :modified_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :created_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :external_system, :text, null: false
      add :external_id, :text, null: false
      add :raw_payload, :map, null: false
      add :source_metadata, :map
      add :cursor, :map
      add :fetched_at, :utc_datetime_usec, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:ingestion_source_objects, [:external_system, :external_id],
             name: "ingestion_source_objects_unique_source_object_index"
           )
  end

  def down do
    drop_if_exists unique_index(:ingestion_source_objects, [:external_system, :external_id],
                     name: "ingestion_source_objects_unique_source_object_index"
                   )

    drop table(:ingestion_source_objects)
  end
end
