defmodule AshEnterprise.Repo.Migrations.RecordReferencePrefixes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:bpmn_instances, "bpmn_instances_definition_id_fkey")

    alter table(:bpmn_instances) do
      modify :definition_id,
             references(:bpmn_definitions,
               column: :id,
               name: "bpmn_instances_definition_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:team_memberships, "team_memberships_team_id_fkey")

    drop constraint(:team_memberships, "team_memberships_user_id_fkey")

    alter table(:team_memberships) do
      modify :user_id,
             references(:users,
               column: :id,
               name: "team_memberships_user_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )

      modify :team_id,
             references(:teams,
               column: :id,
               name: "team_memberships_team_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    drop constraint(:positions, "positions_parent_position_id_fkey")

    alter table(:positions) do
      modify :parent_position_id,
             references(:positions,
               column: :id,
               name: "positions_parent_position_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )
    end

    drop constraint(:teams, "teams_administrator_id_fkey")

    alter table(:teams) do
      modify :administrator_id,
             references(:users,
               column: :id,
               name: "teams_administrator_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:access_requests, "access_requests_scoping_business_unit_id_fkey")

    drop constraint(:access_requests, "access_requests_requested_role_id_fkey")

    alter table(:access_requests) do
      modify :requested_role_id,
             references(:roles,
               column: :id,
               name: "access_requests_requested_role_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nothing
             )

      modify :scoping_business_unit_id,
             references(:business_units,
               column: :id,
               name: "access_requests_scoping_business_unit_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nothing
             )
    end

    drop constraint(:dmn_evaluations, "dmn_evaluations_definition_id_fkey")

    alter table(:dmn_evaluations) do
      modify :definition_id,
             references(:dmn_definitions,
               column: :id,
               name: "dmn_evaluations_definition_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:user_roles, "user_roles_scoping_business_unit_id_fkey")

    drop constraint(:user_roles, "user_roles_role_id_fkey")

    drop constraint(:user_roles, "user_roles_user_id_fkey")

    alter table(:user_roles) do
      modify :user_id,
             references(:users,
               column: :id,
               name: "user_roles_user_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )

      modify :role_id,
             references(:roles,
               column: :id,
               name: "user_roles_role_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )

      modify :scoping_business_unit_id,
             references(:business_units,
               column: :id,
               name: "user_roles_scoping_business_unit_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )
    end

    drop constraint(:bpmn_process_events, "bpmn_process_events_instance_id_fkey")

    alter table(:bpmn_process_events) do
      modify :instance_id,
             references(:bpmn_instances,
               column: :id,
               name: "bpmn_process_events_instance_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:team_roles, "team_roles_scoping_business_unit_id_fkey")

    drop constraint(:team_roles, "team_roles_role_id_fkey")

    drop constraint(:team_roles, "team_roles_team_id_fkey")

    alter table(:team_roles) do
      modify :team_id,
             references(:teams,
               column: :id,
               name: "team_roles_team_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )

      modify :role_id,
             references(:roles,
               column: :id,
               name: "team_roles_role_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )

      modify :scoping_business_unit_id,
             references(:business_units,
               column: :id,
               name: "team_roles_scoping_business_unit_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )
    end

    drop constraint(:bpmn_task_candidates, "bpmn_task_candidates_task_id_fkey")

    alter table(:bpmn_task_candidates) do
      modify :task_id,
             references(:bpmn_human_tasks,
               column: :id,
               name: "bpmn_task_candidates_task_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:process_trigger_dispatches, "process_trigger_dispatches_trigger_id_fkey")

    alter table(:process_trigger_dispatches) do
      modify :trigger_id,
             references(:process_triggers,
               column: :id,
               name: "process_trigger_dispatches_trigger_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:bpmn_tokens, "bpmn_tokens_instance_id_fkey")

    alter table(:bpmn_tokens) do
      modify :instance_id,
             references(:bpmn_instances,
               column: :id,
               name: "bpmn_tokens_instance_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:role_privileges, "role_privileges_privilege_id_fkey")

    drop constraint(:role_privileges, "role_privileges_role_id_fkey")

    alter table(:role_privileges) do
      modify :role_id,
             references(:roles,
               column: :id,
               name: "role_privileges_role_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )

      modify :privilege_id,
             references(:privileges,
               column: :id,
               name: "role_privileges_privilege_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )
    end

    drop constraint(:business_units, "business_units_parent_business_unit_id_fkey")

    alter table(:business_units) do
      modify :parent_business_unit_id,
             references(:business_units,
               column: :id,
               name: "business_units_parent_business_unit_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )
    end

    drop constraint(:users, "users_position_id_fkey")

    drop constraint(:users, "users_manager_id_fkey")

    alter table(:users) do
      modify :manager_id,
             references(:users,
               column: :id,
               name: "users_manager_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :position_id,
             references(:positions,
               column: :id,
               name: "users_position_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:bpmn_human_tasks, "bpmn_human_tasks_token_id_fkey")

    drop constraint(:bpmn_human_tasks, "bpmn_human_tasks_instance_id_fkey")

    alter table(:bpmn_human_tasks) do
      modify :instance_id,
             references(:bpmn_instances,
               column: :id,
               name: "bpmn_human_tasks_instance_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :token_id,
             references(:bpmn_tokens,
               column: :id,
               name: "bpmn_human_tasks_token_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end

  def down do
    drop constraint(:bpmn_human_tasks, "bpmn_human_tasks_instance_id_fkey")

    drop constraint(:bpmn_human_tasks, "bpmn_human_tasks_token_id_fkey")

    alter table(:bpmn_human_tasks) do
      modify :token_id,
             references(:bpmn_tokens,
               column: :id,
               name: "bpmn_human_tasks_token_id_fkey",
               type: :uuid,
               prefix: "canonical"
             )

      modify :instance_id,
             references(:bpmn_instances,
               column: :id,
               name: "bpmn_human_tasks_instance_id_fkey",
               type: :uuid,
               prefix: "canonical"
             )
    end

    drop constraint(:users, "users_manager_id_fkey")

    drop constraint(:users, "users_position_id_fkey")

    alter table(:users) do
      modify :position_id,
             references(:positions,
               column: :id,
               name: "users_position_id_fkey",
               type: :uuid,
               prefix: "canonical"
             )

      modify :manager_id,
             references(:users,
               column: :id,
               name: "users_manager_id_fkey",
               type: :uuid,
               prefix: "canonical"
             )
    end

    drop constraint(:business_units, "business_units_parent_business_unit_id_fkey")

    alter table(:business_units) do
      modify :parent_business_unit_id,
             references(:business_units,
               column: :id,
               name: "business_units_parent_business_unit_id_fkey",
               type: :uuid,
               prefix: "canonical",
               on_delete: :restrict
             )
    end

    drop constraint(:role_privileges, "role_privileges_role_id_fkey")

    drop constraint(:role_privileges, "role_privileges_privilege_id_fkey")

    alter table(:role_privileges) do
      modify :privilege_id,
             references(:privileges,
               column: :id,
               name: "role_privileges_privilege_id_fkey",
               type: :uuid,
               prefix: "canonical",
               on_delete: :restrict
             )

      modify :role_id,
             references(:roles,
               column: :id,
               name: "role_privileges_role_id_fkey",
               type: :uuid,
               prefix: "canonical",
               on_delete: :delete_all
             )
    end

    drop constraint(:bpmn_tokens, "bpmn_tokens_instance_id_fkey")

    alter table(:bpmn_tokens) do
      modify :instance_id,
             references(:bpmn_instances,
               column: :id,
               name: "bpmn_tokens_instance_id_fkey",
               type: :uuid,
               prefix: "canonical"
             )
    end

    drop constraint(:process_trigger_dispatches, "process_trigger_dispatches_trigger_id_fkey")

    alter table(:process_trigger_dispatches) do
      modify :trigger_id,
             references(:process_triggers,
               column: :id,
               name: "process_trigger_dispatches_trigger_id_fkey",
               type: :uuid,
               prefix: "canonical"
             )
    end

    drop constraint(:bpmn_task_candidates, "bpmn_task_candidates_task_id_fkey")

    alter table(:bpmn_task_candidates) do
      modify :task_id,
             references(:bpmn_human_tasks,
               column: :id,
               name: "bpmn_task_candidates_task_id_fkey",
               type: :uuid,
               prefix: "canonical"
             )
    end

    drop constraint(:team_roles, "team_roles_team_id_fkey")

    drop constraint(:team_roles, "team_roles_role_id_fkey")

    drop constraint(:team_roles, "team_roles_scoping_business_unit_id_fkey")

    alter table(:team_roles) do
      modify :scoping_business_unit_id,
             references(:business_units,
               column: :id,
               name: "team_roles_scoping_business_unit_id_fkey",
               type: :uuid,
               prefix: "canonical",
               on_delete: :restrict
             )

      modify :role_id,
             references(:roles,
               column: :id,
               name: "team_roles_role_id_fkey",
               type: :uuid,
               prefix: "canonical",
               on_delete: :delete_all
             )

      modify :team_id,
             references(:teams,
               column: :id,
               name: "team_roles_team_id_fkey",
               type: :uuid,
               prefix: "canonical",
               on_delete: :delete_all
             )
    end

    drop constraint(:bpmn_process_events, "bpmn_process_events_instance_id_fkey")

    alter table(:bpmn_process_events) do
      modify :instance_id,
             references(:bpmn_instances,
               column: :id,
               name: "bpmn_process_events_instance_id_fkey",
               type: :uuid,
               prefix: "canonical"
             )
    end

    drop constraint(:user_roles, "user_roles_user_id_fkey")

    drop constraint(:user_roles, "user_roles_role_id_fkey")

    drop constraint(:user_roles, "user_roles_scoping_business_unit_id_fkey")

    alter table(:user_roles) do
      modify :scoping_business_unit_id,
             references(:business_units,
               column: :id,
               name: "user_roles_scoping_business_unit_id_fkey",
               type: :uuid,
               prefix: "canonical",
               on_delete: :restrict
             )

      modify :role_id,
             references(:roles,
               column: :id,
               name: "user_roles_role_id_fkey",
               type: :uuid,
               prefix: "canonical",
               on_delete: :delete_all
             )

      modify :user_id,
             references(:users,
               column: :id,
               name: "user_roles_user_id_fkey",
               type: :uuid,
               prefix: "canonical",
               on_delete: :delete_all
             )
    end

    drop constraint(:dmn_evaluations, "dmn_evaluations_definition_id_fkey")

    alter table(:dmn_evaluations) do
      modify :definition_id,
             references(:dmn_definitions,
               column: :id,
               name: "dmn_evaluations_definition_id_fkey",
               type: :uuid,
               prefix: "canonical"
             )
    end

    drop constraint(:access_requests, "access_requests_requested_role_id_fkey")

    drop constraint(:access_requests, "access_requests_scoping_business_unit_id_fkey")

    alter table(:access_requests) do
      modify :scoping_business_unit_id,
             references(:business_units,
               column: :id,
               name: "access_requests_scoping_business_unit_id_fkey",
               type: :uuid,
               prefix: "canonical",
               on_delete: :nothing
             )

      modify :requested_role_id,
             references(:roles,
               column: :id,
               name: "access_requests_requested_role_id_fkey",
               type: :uuid,
               prefix: "canonical",
               on_delete: :nothing
             )
    end

    drop constraint(:teams, "teams_administrator_id_fkey")

    alter table(:teams) do
      modify :administrator_id,
             references(:users,
               column: :id,
               name: "teams_administrator_id_fkey",
               type: :uuid,
               prefix: "canonical"
             )
    end

    drop constraint(:positions, "positions_parent_position_id_fkey")

    alter table(:positions) do
      modify :parent_position_id,
             references(:positions,
               column: :id,
               name: "positions_parent_position_id_fkey",
               type: :uuid,
               prefix: "canonical",
               on_delete: :restrict
             )
    end

    drop constraint(:team_memberships, "team_memberships_user_id_fkey")

    drop constraint(:team_memberships, "team_memberships_team_id_fkey")

    alter table(:team_memberships) do
      modify :team_id,
             references(:teams,
               column: :id,
               name: "team_memberships_team_id_fkey",
               type: :uuid,
               prefix: "canonical",
               on_delete: :delete_all
             )

      modify :user_id,
             references(:users,
               column: :id,
               name: "team_memberships_user_id_fkey",
               type: :uuid,
               prefix: "canonical",
               on_delete: :delete_all
             )
    end

    drop constraint(:bpmn_instances, "bpmn_instances_definition_id_fkey")

    alter table(:bpmn_instances) do
      modify :definition_id,
             references(:bpmn_definitions,
               column: :id,
               name: "bpmn_instances_definition_id_fkey",
               type: :uuid,
               prefix: "canonical"
             )
    end
  end
end
