defmodule AshEnterprise.Repo.Migrations.AddProjectedUsers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:projected_users, primary_key: false) do
      add :organization_id, :uuid, null: false
      add :owning_business_unit_id, :uuid
      add :lifecycle_status, :text, null: false, default: "active"
      add :version_number, :bigint, null: false, default: 1
      add :import_sequence_number, :bigint
      add :overridden_created_on, :utc_datetime_usec
      add :modified_on_behalf_by_id, :uuid
      add :created_on_behalf_by_id, :uuid
      add :modified_by_id, :uuid
      add :created_by_id, :uuid

      add :modified_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :created_on, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :id, :uuid, null: false, primary_key: true
      add :legacy_id, :bigint, null: false
      add :login, :text
      add :email, :citext
      add :full_name, :text
      add :legacy_state, :text
      add :projected_at, :utc_datetime_usec, null: false
      add :archived_at, :utc_datetime_usec
    end

    create unique_index(:projected_users, [:organization_id, :legacy_id],
             name: "projected_users_from_legacy_index"
           )
  end

  def down do
    drop_if_exists unique_index(:projected_users, [:organization_id, :legacy_id],
                     name: "projected_users_from_legacy_index"
                   )

    drop table(:projected_users)
  end
end
