defmodule AshEnterprise.Repo.Migrations.AddComplianceLedger do
  @moduledoc """
  Strangler compatibility layer, generated by `mix ash_strangler.gen.migration`.

  Covers: AshEnterprise.Legacy.User

  Regenerate rather than hand-editing. Every statement is idempotent
  (`CREATE OR REPLACE`, `IF NOT EXISTS`), so re-running this after a mapping
  change is safe.
  """

  use Ecto.Migration

  def up do
    execute("""
    CREATE SCHEMA IF NOT EXISTS "strangler";
    """)

    execute("""
    CREATE OR REPLACE VIEW "strangler"."users" AS
    SELECT
      uuid_generate_v5('ce41843a-c056-4c3e-9c79-50e7e5f4887c'::uuid, 'legacy.users:' || id::text) AS id,
      id AS __legacy_id,
      ('00000000-0000-0000-0000-0000000000fe')::uuid AS organization_id,
      ('00000000-0000-0000-0000-0000000000fd')::uuid AS owning_business_unit_id,
      (CASE WHEN (state = 'active') THEN ('active')::text ELSE ('inactive')::text END) AS lifecycle_status,
      1 AS version_number,
      NULL AS import_sequence_number,
      NULL AS overridden_created_on,
      NULL AS modified_on_behalf_by_id,
      NULL AS created_on_behalf_by_id,
      NULL AS modified_by_id,
      NULL AS created_by_id,
      (updated_at AT TIME ZONE 'UTC') AS modified_on,
      (created_at AT TIME ZONE 'UTC') AS created_on,
      id AS legacy_id,
      login AS login,
      (email)::citext AS email,
      (coalesce(first_name, '') || (' ' || coalesce(last_name, ''))) AS full_name,
      (state)::text AS legacy_state,
      (deleted_at AT TIME ZONE 'UTC') AS archived_at
    FROM legacy.users;
    """)

    execute("""
    CREATE INDEX IF NOT EXISTS strangler_users_key_idx ON legacy.users
      (uuid_generate_v5('ce41843a-c056-4c3e-9c79-50e7e5f4887c'::uuid, 'legacy.users:' || id::text));
    """)

    execute("""
    CREATE TABLE IF NOT EXISTS "public"."legacy_change_events" (
      id bigserial PRIMARY KEY,
      source_system text,
      source_schema text NOT NULL,
      source_table text NOT NULL,
      operation text NOT NULL,
      primary_key jsonb NOT NULL,
      old_row jsonb,
      new_row jsonb,
      changed_columns jsonb,
      transaction_id bigint,
      transaction_timestamp timestamptz,
      source_user text,
      source_request_id text,
      source_correlation_id text,
      actor_confidence text,
      emitted_at timestamptz NOT NULL DEFAULT now(),
      processed_at timestamptz
    )
    """)

    execute("""
    CREATE INDEX IF NOT EXISTS legacy_change_events_unprocessed_idx
      ON "public"."legacy_change_events" (processed_at)
      WHERE processed_at IS NULL
    """)

    execute("""
    CREATE OR REPLACE FUNCTION "public"."strangler_ledger_legacy_users"() RETURNS trigger AS $strangler$
    DECLARE
      event_id bigint;
      affected record;
      old_row jsonb;
      new_row jsonb;
      changed jsonb;
    BEGIN
      affected := COALESCE(NEW, OLD);

      IF (TG_OP = 'DELETE') THEN
        old_row := to_jsonb(OLD);
        new_row := NULL;
        changed := NULL;
      ELSIF (TG_OP = 'INSERT') THEN
        old_row := NULL;
        new_row := to_jsonb(NEW);
        changed := new_row;
      ELSE
        old_row := to_jsonb(OLD);
        new_row := to_jsonb(NEW);
        changed := (
          SELECT COALESCE(jsonb_object_agg(pair.key, pair.value), '{}'::jsonb)
            FROM jsonb_each(new_row) AS pair
           WHERE (old_row -> pair.key) IS DISTINCT FROM pair.value
        );
      END IF;

      -- Committed WITH the legacy write or not at all: that is the whole
      -- guarantee the ledger exists for, and it is why this is a synchronous
      -- insert rather than a queue.
      INSERT INTO "public"."legacy_change_events"
        (source_schema, source_table, operation, primary_key, old_row, new_row,
         changed_columns, transaction_id, transaction_timestamp)
      VALUES
        (TG_TABLE_SCHEMA, TG_TABLE_NAME, lower(TG_OP),
         jsonb_build_object('id', affected.id),
         old_row, new_row, changed,
         txid_current(), transaction_timestamp())
      RETURNING id INTO event_id;

      -- The wake, key-only. The event id is a bigint, so the payload is a
      -- handful of bytes no matter how wide the row is -- the 7999-byte
      -- pg_notify ceiling aborts the LEGACY application's transaction, and a
      -- drain re-reads the durable row anyway.
      PERFORM pg_notify('ash_strangler', 'wake:' || event_id);

      -- The return value of an AFTER row trigger is ignored.
      RETURN NULL;
    END $strangler$ LANGUAGE plpgsql;
    """)

    execute("""
    CREATE OR REPLACE TRIGGER "strangler_ledger_legacy_users"
      AFTER INSERT OR UPDATE OR DELETE ON legacy.users
      FOR EACH ROW EXECUTE FUNCTION "public"."strangler_ledger_legacy_users"();
    """)

    # One-time cleanup, hand-added: the 20260819 read-model migration installed
    # a row-data-payload notify trigger (`strangler_users_notify`). With
    # `ledger?` the ledger function above is also the notifier, so the old
    # trigger would double-fire on every legacy write and reintroduce the
    # 7999-byte payload ceiling it existed to hit. The generator does not know
    # its own predecessor, so the drop is written here rather than upstream.
    execute("""
    DROP TRIGGER IF EXISTS "strangler_users_notify" ON legacy.users;
    """)

    execute("""
    DROP FUNCTION IF EXISTS "strangler"."strangler_users_notify"() CASCADE;
    """)
  end

  def down do
    execute("""
    DO $strangler$
    BEGIN
      IF to_regclass('legacy.users') IS NOT NULL THEN
        EXECUTE 'DROP TRIGGER IF EXISTS "strangler_ledger_legacy_users" ON legacy.users';
      END IF;
    END $strangler$;
    """)

    execute("""
    DROP FUNCTION IF EXISTS "public"."strangler_ledger_legacy_users"() CASCADE;
    """)

    execute("""
    DROP INDEX IF EXISTS "public"."legacy_change_events_unprocessed_idx";
    """)

    execute("""
    DROP TABLE IF EXISTS "public"."legacy_change_events";
    """)

    execute("""
    DROP INDEX IF EXISTS legacy.strangler_users_key_idx;
    """)

    execute("""
    DROP VIEW IF EXISTS "strangler"."users";
    """)

    execute("""
    DO $strangler$
    BEGIN
      IF NOT EXISTS (
        SELECT 1
          FROM pg_class c
          JOIN pg_namespace n ON n.oid = c.relnamespace
         WHERE n.nspname = 'strangler'
      ) AND NOT EXISTS (
        SELECT 1
          FROM pg_proc p
          JOIN pg_namespace n ON n.oid = p.pronamespace
         WHERE n.nspname = 'strangler'
      ) THEN
        EXECUTE 'DROP SCHEMA IF EXISTS "strangler"';
      END IF;
    END $strangler$;
    """)
  end
end
